class FontList
  def full_list
    [
      ["Luckiest Guy", "'Luckiest Guy', cursive"], ["Graffiti font", "'Graffiti font', sans-serif"], ["Erica One", "'Erica One', cursive, sans-serif"],
      ["Calligraffitti", "'Calligraffitti', cursive"], ["Roboto", "Roboto, sans-serif"], ["Oswald", "Oswald, sans-serif"], ["Neue Yokarto", "'Neue Yokarto', sans-serif"],
      ["Neue Yokarto Spurs", "'Neue Yokarto Spurs', sans-serif"], ["Smiling Animal", "'Smiling Animal', sans-serif"], ["Upper Punch", "'Upper Punch', sans-serif"],
      ["Upper Punch 3D", "'Upper Punch 3D', sans-serif"], ["Upper Punch 3D Italic", "'Upper Punch 3D Italic', sans-serif"], ["Redro", "'Redro', sans-serif"],
      ["Upper Punch All Caps Italic", "'Upper Punch All Caps Italic', sans-serif"], ["Upper Punch Condensed", "'Upper Punch Condensed', sans-serif"], 
      ["Upper Punch Condensed Italic", "'Upper Punch Condensed Italic', sans-serif"], ["Upper Punch Expanded", "'Upper Punch Expanded', sans-serif"], 
      ["Upper Punch Expanded Italic", "'Upper Punch Expanded Italic', sans-serif"], ["Upper Punch Expanded", "'Upper Punch Expanded', sans-serif"],
      ["Upper Punch Gradient", "'Upper Punch Gradient', sans-serif"], ["Upper Punch Gradient Italic", "'Upper Punch Gradient Italic', sans-serif"],
      ["Upper Punch Italic", "'Upper Punch Italic', sans-serif"], ["Upper Punch Laser", "'Upper Punch Laser', sans-serif"], ["Charter BT", "'Charter BT', sans-serif"],
      ["Upper Punch Laser Italic", "'Upper Punch Laser Italic', sans-serif"], ["Upper Punch Leftalic", "'Upper Punch Leftalic', sans-serif"],
      ["Upper Punch Semi-Italic", "'Upper Punch Semi-Italic', sans-serif"], ["Upper Punch Semi-Leftalic", "'Upper Punch Semi-Leftalic', sans-serif"],
      ["Upper Punch Spaced", "'Upper Punch Spaced', sans-serif"], ["Upper Punch Spaced Italic", "'Upper Punch Spaced Italic', sans-serif"],
      ["Upper Punch Super-Italic", "'Upper Punch Super-Italic', sans-serif"], ["Upper Punch Super-Leftalic", "'Upper Punch Super-Leftalic', sans-serif"],
      ["Childzone", "'Childzone', sans-serif"], ["Jabgiki", "'Jabgiki', sans-serif"], ["Ultimate", "'Ultimate', sans-serif"], ["Hi Ashoka", "'Hi Ashoka', sans-serif"],
      ["MISAKI", "'MISAKI', sans-serif"], ["Mentimun", "'Mentimun', sans-serif"], ["Telford Town", "'Telford Town', sans-serif"], ["Deltha", "'Deltha', sans-serif"],
      ["Blenny Trial", "'Blenny Trial', sans-serif"], ["Decision Making", "'Decision Making', sans-serif"], ["Millgary", "'Millgary', sans-serif"], 
      ["Migoes", "'Migoes', sans-serif"], ["Yonder Blue", "'Yonder Blue', sans-serif"], ["Yonder Blue 3D", "'Yonder Blue 3D', sans-serif"], 
      ["Yonder Blue 3D Straight", "'Yonder Blue 3D Straight', sans-serif"], ["Yonder Blue Condensed", "'Yonder Blue Condensed', sans-serif"],
      ["Yonder Blue Condensed Straight", "'Yonder Blue Condensed Straight', sans-serif"], ["Yonder Blue Expanded", "'Yonder Blue Expanded', sans-serif"], 
      ["Yonder Blue Expanded Straight", "'Yonder Blue Expanded Straight', sans-serif"], ["Yonder Blue Gradient", "'Yonder Blue Gradient', sans-serif"], 
      ["Yonder Blue Gradient 2", "'Yonder Blue Gradient 2', sans-serif"], ["Yonder Blue Halftone", "'Yonder Blue Halftone', sans-serif"], 
      ["Yonder Blue Halftone 2", "'Yonder Blue Halftone 2', sans-serif"], ["Yonder Blue Italic", "'Yonder Blue Italic', sans-serif"], ["WrittenFrax", "'WrittenFrax', sans-serif"],
      ["Yonder Blue Laser", "'Yonder Blue Laser', sans-serif"], ["Yonder Blue Leftalic", "'Yonder Blue Leftalic', sans-serif"], ["Kenarock", "'Kenarock', sans-serif"],
      ["Yonder Blue Semi-Leftalic", "'Yonder Blue Semi-Leftalic', sans-serif"], ["Yonder Blue Semi-Straight", "'Yonder Blue Semi-Straight', sans-serif"], 
      ["Yonder Blue Spaced", "'Yonder Blue Spaced', sans-serif"], ["Yonder Blue Spaced Straight", "'Yonder Blue Spaced Straight', sans-serif"],
      ["Yonder Blue Straight", "'Yonder Blue Straight', sans-serif"], ["Krisan", "'Krisan', sans-serif"], ["Melgis Free", "'Melgis Free', sans-serif"],
      ["Geajer", "'Geajer', sans-serif"], ["CHOOSE ELEGANT", "'CHOOSE ELEGANT', sans-serif"], ["Endinge", "'e Endinge', sans-serif"], ["Syakifah", "'Syakifah', sans-serif"],
      ["Fortune Soldier", "'Fortune Soldier', sans-serif"], ["Fortune Soldier 3D", "'Fortune Soldier 3D', sans-serif"], ["Pommern Gotisch", "'Pommern Gotisch', sans-serif"],
      ["Fortune Soldier Bevel", "'Fortune Soldier Bevel', sans-serif"], ["Fortune Soldier Chrome", "'Fortune Soldier Chrome', sans-serif"], 
      ["Fortune Soldier Gradient", "'Fortune Soldier Gradient', sans-serif"], ["Fortune Soldier Halftone", "'Fortune Soldier Halftone', sans-serif"], 
      ["Fortune Soldier Laser", "'Fortune Soldier Laser', sans-serif"], ["Fortune Soldier Punch", "'Fortune Soldier Punch', sans-serif"], ["ALEWISDODI", "'ALEWISDODI', sans-serif"],
      ["Fortune Soldier Title", "'Fortune Soldier Title', sans-serif"], ["Fortune Soldier 3D Italic", "'Fortune Soldier 3D Italic', sans-serif"],
      ["Fortune Soldier Bevel Italic", "'Fortune Soldier Bevel Italic', sans-serif"], ["Fortune Soldier Chrome Italic", "'Fortune Soldier Chrome Italic', sans-serif"],
      ["Fortune Soldier Condensed", "'Fortune Soldier Condensed', sans-serif"], ["Fortune Soldier Condensed Ital", "'Fortune Soldier Condensed Ital', sans-serif"],
      ["Fortune Soldier Expanded", "'Fortune Soldier Expanded', sans-serif"], ["Fortune Soldier Expanded Italic", "'Fortune Soldier Expanded Italic', sans-serif"],
      ["Fortune Soldier Gradient Italic", "'Fortune Soldier Gradient Italic', sans-serif"], ["Fortune Soldier Italic", "'Fortune Soldier Italic', sans-serif"],
      ["Fortune Soldier Laser Italic", "'Fortune Soldier Laser Italic', sans-serif"], ["Fortune Soldier Leftalic", "'Fortune Soldier Leftalic', sans-serif"],
      ["Fortune Soldier Punch Italic", "'Fortune Soldier Punch Italic', sans-serif"], ["Fortune Soldier Semi-Italic", "'Fortune Soldier Semi-Italic', sans-serif"],
      ["Fortune Soldier Super-Italic", "'Fortune Soldier Super-Italic', sans-serif"], ["Fortune Soldier Title Italic", "'Fortune Soldier Title Italic', sans-serif"],
      ["Zidan", "'Zidan', sans-serif"], ["Arrancar", "'Arrancar', sans-serif"], ["Elephant Beetle", "'e Elephant Beetle', sans-serif"], ["Egima", "'e Egima', sans-serif"], 
      ["HaveFun", "'HaveFun', sans-serif"], ["Merry Land", "'Merry Land', sans-serif"], ["Monash", "'Monash', sans-serif"], ["Sang Jutawan", "'Sang Jutawan', sans-serif"], 
      ["NiseSonicBattle", "'NiseSonicBattle', sans-serif"], ["Rambors", "'Rambors', sans-serif"], ["Wizard", "'Wizard', sans-serif"], ["Scarlet", "'Scarlet', sans-serif"], 
      ["Gaftora", "'Gaftora', sans-serif"], ["Adittab Marirah", "'Adittab Marirah', sans-serif"], ["Largely Elegant", "'Largely Elegant', sans-serif"], 
      ["Empire Kingdom", "'e Empire Kingdom', sans-serif"], ["Brown Fox", "'Brown Fox', sans-serif"], ["Belgan Aesthetic", "'Belgan Aesthetic', sans-serif"],
      ["Upper Punch Gradient", "'Upper Punch Gradient', sans-serif"], ["Upper Punch Gradient Italic", "'Upper Punch Gradient Italic', sans-serif"], 
      ["Piranya", "'Piranya', sans-serif"], ["Dreams Liem", "'Dreams Liem', sans-serif"], ["Al Ragas", "'Al Ragas', sans-serif"], ["Backsteal", "'Backsteal', sans-serif"],
      ["Ethnic Wind", "'e Ethnic Wind', sans-serif"], ["El Katana Alt Flo Medium DEMO", "'El Katana Alt Flo Medium DEMO', sans-serif"], ["MOTO VERSE", "'MOTO VERSE', sans-serif"],
      ["Activists", "'Activists', sans-serif"], ["New MOTOR", "'New MOTOR', sans-serif"], ["SingleGhost regular", "'SingleGhost regular', sans-serif"], 
      ["Blacklet", "'Blacklet', sans-serif"], ["Pineapple Demo", "'Pineapple Demo', sans-serif"], ["Dreamwood DEMO", "'Dreamwood DEMO', sans-serif"], 
      ["HelloEtchASketch", "'HelloEtchASketch', sans-serif"], ["MicEdge", "'MicEdge', sans-serif"], ["BLUE OCEAN", "'BLUE OCEAN', sans-serif"], ["Borned", "'Borned', sans-serif"], 
      ["Angas", "'Angas', sans-serif"], ["Vintage King", "'Vintage King', sans-serif"], ["Estebu", "'e Estebu', sans-serif"], ["FILAGO", "'FILAGO', sans-serif"], 
      ["KAPPA", "'KAPPA', sans-serif"], ["Technocra", "'Technocra', sans-serif"], ["SUPERBOLT", "'SUPERBOLT', sans-serif"], ["Space Monkey", "'Space Monkey', sans-serif"],
      ["White Block Personal Use", "'White Block Personal Use', sans-serif"], ["Rebellion", "'Rebellion', sans-serif"], ["Speedeasy Speedy", "'Speedeasy Speedy', sans-serif"],
      ["Speedeasy", "'Speedeasy', sans-serif"], ["Cyrivendell", "'Cyrivendell', sans-serif"], ["Dangerbot", "'Dangerbot', sans-serif"], ["Dangerbot 3D", "'Dangerbot 3D', sans-serif"],
      ["Dangerbot Chrome", "'Dangerbot Chrome', sans-serif"], ["Dangerbot Engraved", "'Dangerbot Engraved', sans-serif"], ["Dangerbot Gradient", "'Dangerbot Gradient', sans-serif"], 
      ["Dangerbot Halftone", "'Dangerbot Halftone', sans-serif"], ["Dangerbot Laser", "'Dangerbot Laser', sans-serif"], ["Dangerbot Punch", "'Dangerbot Punch', sans-serif"],
      ["Dangerbot 3D Expanded", "'Dangerbot 3D Expanded', sans-serif"], ["Dangerbot Condensed", "'Dangerbot Condensed', sans-serif"], ["Cyberfall", "'Cyberfall', sans-serif"],
      ["Dangerbot Expanded", "'Dangerbot Expanded', sans-serif"], ["Dangerbot Expanded Italic", "'Dangerbot Expanded Italic', sans-serif"], ["RoadTest", "'RoadTest', sans-serif"], 
      ["Dangerbot Expanded Laser", "'Dangerbot Expanded Laser', sans-serif"], ["Dangerbot Expanded Outline", "'Dangerbot Expanded Outline', sans-serif"], 
      ["Dangerbot Gradient Expanded", "'Dangerbot Gradient Expanded', sans-serif"], ["Rapier Zero Hollow", "'Rapier Zero Hollow', sans-serif"], 
      ["Dangerbot Italic", "'Dangerbot Italic', sans-serif"], ["Dangerbot Outline", "'Dangerbot Outline', sans-serif"], ["Rapier Zero", "'Rapier Zero', sans-serif"],
      ["Dangerbot Extra-Expanded", "'Dangerbot Extra-Expanded', sans-serif"], ["Star Wuarras", "'Star Wuarras', sans-serif"], ["hardcorium", "'hardcorium', sans-serif"], 
      ["Aesthetic DEMO", "'Aesthetic DEMO', sans-serif"], ["Kalmari", "'Kalmari', sans-serif"], ["Lux Contra Tenebras", "'Lux Contra Tenebras', sans-serif"], 
      ["Lux Contra Tenebras 3D", "'Lux Contra Tenebras 3D', sans-serif"], ["Lux Contra Tenebras Rotated", "'Lux Contra Tenebras Rotated', sans-serif"], 
      ["Lux Contra Tenebras 3D Italic", "'Lux Contra Tenebras 3D Italic', sans-serif"], ["Lux Contra Tenebras Condensed", "'Lux Contra Tenebras Condensed', sans-serif"], 
      ["Lux Contra Tenebras Condensed Italic", "'Lux Contra Tenebras Condensed Italic', sans-serif"], ["Lux Contra Tenebras Expanded", "'Lux Contra Tenebras Expanded', sans-serif"],
      ["Lux Contra Tenebras Expanded Italic", "'Lux Contra Tenebras Expanded Italic', sans-serif"], ["Lux Contra Tenebras Italic", "'Lux Contra Tenebras Italic', sans-serif"], 
      ["Lux Contra Tenebras Leftalic", "'Lux Contra Tenebras Leftalic', sans-serif"], ["Lux Contra Tenebras Rotatalic", "'Lux Contra Tenebras Rotatalic', sans-serif"],
      ["Regothic", "'Regothic', sans-serif"], ["Dioszeghiensis Rg", "'Dioszeghiensis Rg', sans-serif"], ["Gotisch Weiss UNZ1A", "'Gotisch Weiss UNZ1A', sans-serif"],
      ["Tfu Tfu", "'Tfu Tfu', sans-serif"], ["Bullgine DEMO", "'Bullgine DEMO', sans-serif"], ["Offenbacher Reform CAT", "'Offenbacher Reform CAT', sans-serif"], 
      ["Puppeteer", "'Puppeteer', sans-serif"], ["Poppl Fraktur CAT", "'Poppl Fraktur CAT', sans-serif"], ["Kanzleyrath", "'Kanzleyrath', sans-serif"], 
      ["Argor Fast Scaqh", "'Argor Fast Scaqh', sans-serif"], ["Lyric Poetry", "'Lyric Poetry', sans-serif"], ["Redro tall", "'Redro tall', sans-serif"],
      ["Jena Gotisch", "'Jena Gotisch', sans-serif"], ["Kanzlei", "'Kanzlei', sans-serif"], ["KoenigsbergerGotisch", "'KoenigsbergerGotisch', sans-serif"],
      ["Kabinett Fraktur", "'Kabinett Fraktur', sans-serif"], ["Guerra_Santa", "'Guerra_Santa', sans-serif"], ["Old Deutschland", "'Old Deutschland', sans-serif"],
      ["Barloesius Schrift", "'Barloesius Schrift', sans-serif"], ["Hamburger Schwabacher Druckrauh", "'Hamburger Schwabacher Druckrauh', sans-serif"],
      ["FrederickText", "'FrederickText', sans-serif"], ["Des Malers Fraktur", "'Des Malers Fraktur', sans-serif"], ["Old Wise Sketch", "'Old Wise Sketch', sans-serif"],
      ["OffenbacherSchwabacherCAT", "'OffenbacherSchwabacherCAT', sans-serif"], ["Hopeful Christmas Solid", "'Hopeful Christmas Solid', sans-serif"],
      ["CAT FrankenDeutsch", "'CAT FrankenDeutsch', sans-serif"], ["Gypsy Killer", "'Gypsy Killer', sans-serif"], ["Gypsy Killer Chrome", "'Gypsy Killer Chrome', sans-serif"], 
      ["Gypsy Killer Gradient", "'Gypsy Killer Gradient', sans-serif"], ["Gypsy Killer Half-Tone", "'Gypsy Killer Half-Tone', sans-serif"], 
      ["Monash", "'Monash', sans-serif"], ["Sang Jutawan", "'Sang Jutawan', sans-serif"], ["Gypsy Killer Laser", "'Gypsy Killer Laser', sans-serif"], 
      ["Gypsy Killer Outline", "'Gypsy Killer Outline', sans-serif"], ["Gypsy Killer Platinum", "'Gypsy Killer Platinum', sans-serif"], ["HelloMello", "'HelloMello', sans-serif"],
      ["Gypsy Killer 3D", "'Gypsy Killer 3D', sans-serif"], ["Gypsy Killer Academy", "'Gypsy Killer Academy', sans-serif"], ["Older Dictator", "'Older Dictator', sans-serif"],
      ["Gypsy Killer Bullet", "'Gypsy Killer Bullet', sans-serif"], ["Gypsy Killer Bullet Italic", "'Gypsy Killer Bullet Italic', sans-serif"], 
      ["Gypsy Killer Chrome Italic", "'Gypsy Killer Chrome Italic', sans-serif"], ["Gypsy Killer Condensed", "'Gypsy Killer Condensed', sans-serif"], 
      ["Gypsy Killer Condensed Italic", "'Gypsy Killer Condensed Italic', sans-serif"], ["Gypsy Killer Expanded", "'Gypsy Killer Expanded', sans-serif"], 
      ["Gypsy Killer Expanded Italic", "'Gypsy Killer Expanded Italic', sans-serif"], ["Gypsy Killer Gradient Italic", "'Gypsy Killer Gradient Italic', sans-serif"], 
      ["Gypsy Killer Half-Tone Italic", "'Gypsy Killer Half-Tone Italic', sans-serif"], ["Gypsy Killer Laser Italic", "'Gypsy Killer Laser Italic', sans-serif"],
      ["Gypsy Killer Italic", "'Gypsy Killer Italic', sans-serif"], ["Gypsy Killer Outline Italic", "'Gypsy Killer Outline Italic', sans-serif"], 
      ["Gypsy Killer Leftalic", "'Gypsy Killer Leftalic', sans-serif"], ["Gypsy Killer Platinum Italic", "'Gypsy Killer Platinum Italic', sans-serif"], 
      ["Gypsy Killer 3D Italic", "'Gypsy Killer 3D Italic', sans-serif"], ["Gypsy Killer Academy Italic", "'Gypsy Killer Academy Italic', sans-serif"], 
      ["GregorianFLF", "'GregorianFLF', sans-serif"], ["Bastille Vredeburg Demo", "'Bastille Vredeburg Demo', sans-serif"], ["Old Europe", "'Old Europe', sans-serif"], 
      ["HansaGotisch", "'HansaGotisch', sans-serif"], ["AuldMagick", "'AuldMagick', sans-serif"], ["AuldMagick Bold", "'AuldMagick Bold', sans-serif"], 
      ["Galactic Spaceport", "'Galactic Spaceport', sans-serif"], ["Pro Display tfb", "'Pro Display tfb', sans-serif"], ["News Board Tfb", "'News Board Tfb', sans-serif"], 
      ["I Ging", "'I Ging', sans-serif"], ["The Display St", "'The Display St', sans-serif"], ["Beato", "'Beato', sans-serif"], ["Musylius", "'Musylius', sans-serif"],
      ["Our Display St", "'Our Display St', sans-serif"], ["Other Display St", "'Other Display St', sans-serif"], ["Pixel Countdown", "'Pixel Countdown', sans-serif"], 
      ["D Bagues", "'JD Bagues', sans-serif"], ["New Watch", "'New Watch', sans-serif"], ["Pixel LCD7", "'Pixel LCD7', sans-serif"], ["Kirsty", "'Kirsty', sans-serif"], 
      ["New X Digital tfb", "'New X Digital tfb', sans-serif"], ["New X Digital tfb Light", "'New X Digital tfb Light', sans-serif"], ["ResotEPearl", "'ResotEPearl', sans-serif"],
      ["New X Digital tfb Hollow", "'New X Digital tfb Hollow', sans-serif"], ["Darkwell DEM", "'Darkwell DEMO', sans-serif"], ["Crewniverse", "'Crewniverse', sans-serif"], 
      ["Foxbot", "'Foxbot', sans-serif"], ["Alleman", "'Alleman', sans-serif"], ["Tanjiro", "'Tanjiro', sans-serif"], ["Citation", "'Citation', sans-serif"],  
      ["Gladista Script", "'Gladista Script', sans-serif"], ["Dartisia', sans-serif", "'Dartisia', sans-serif"], ["alyssum demo", "'alyssum demo', sans-serif"], 
      ["Alliando", "'Alliando', sans-serif"], ["Lanjutin Free Demo", "'Lanjutin Free Demo', sans-serif"], ["Besttia Brush", "'Besttia Brush', sans-serif"], 
      ["Basting Brush", "'Basting Brush', sans-serif"], ["Basting Brush Underlines", "'Basting Brush Underlines', sans-serif"], ["Black mud", "'Black mud', sans-serif"],
      ["Black mud Underlines", "'Black mud Underlines', sans-serif"], ["Celtia Script", "'Celtia Script', sans-serif"], ["Choose Time", "'Choose Time', sans-serif"], 
      ["Choose Time Underlines", "'Choose Time Underlines', sans-serif"], ["Clock bird", "'Clock bird', sans-serif"], ["Clock Bird Underlines", "'Clock Bird Underlines', sans-serif"], 
      ["Emilston", "'Emilston', sans-serif"], ["Emilston Underlines", "'Emilston Underlines', sans-serif"], ["Fellya", "'Fellya', sans-serif"], 
      ["Heating Elegant", "'Heating Elegant', sans-serif"], ["zai Calligraphy Script Handwritten", "'zai Calligraphy Script Handwritten', sans-serif"], 
      ["Bad Ride", "'Bad Ride', sans-serif"], ["Brocklyns", "'Brocklyns', sans-serif"], ["Blush Script", "'Blush Script', sans-serif"], ["INICIO", "'INICIO', sans-serif"],
      ["Bride", "'Bride', sans-serif"], ["Bellagia Script", "'Bellagia Script', sans-serif"], ["Fargo Bold Italic PERSONAL USE", "'Fargo Bold Italic PERSONAL USE', sans-serif"], 
      ["Fargo Bold PERSONAL USE", "'Fargo Bold PERSONAL USE', sans-serif"], ["Balnuettes", "'Balnuettes', sans-serif"], ["Mega Brush", "'Mega Brush', sans-serif"], 
      ["Attacks", "'Attacks', sans-serif"], ["Mechaniclove", "'Mechaniclove', sans-serif"], ["Mandailing script memo", "'Mandailing script memo', sans-serif"], 
      ["Thom Rodger", "'Thom Rodger', sans-serif"], ["Naishila Dancing Script", "'Naishila Dancing Script', sans-serif"], ["Roschild", "'Roschild', sans-serif"], 
      ["Hochagi", "'Hochagi', sans-serif"], ["Maferic Italic", "'Maferic Italic', sans-serif"], ["Angon", "'Angon', sans-serif"], ["Lunch time", "'Lunch time', sans-serif"],
      ["Fimlen", "'Fimlen', sans-serif"], ["Enriqueta", "'Enriqueta', sans-serif"], ["DM Serif Display", "'DM Serif Display', sans-serif"], 
      ["Jomolhari", "'Jomolhari', sans-serif"], ["Brian James Contour", "'Brian James Contour', sans-serif"], ["Brian James Condensed", "'Brian James Condensed', sans-serif"], 
      ["Banbury", "'Banbury', sans-serif"], ["Menschor", "'Menschor', sans-serif"], ["Hiroshige LT Medium", "'Hiroshige LT Medium', sans-serif"],  
      ["Kirsty Ink", "'Kirsty Ink', sans-serif"], ["BodinSmall", "'BodinSmall', sans-serif"], ["CocosOldDB", "'CocosOldDB', sans-serif"], ["Meltland", "'Meltland', sans-serif"],
      ["ImperatorBronzeSmallCaps", "'ImperatorBronzeSmallCaps', sans-serif"], ["Endora", "'Endora', sans-serif"], ["Erie Roman", "'Erie Roman', sans-serif"], 
      ["Maxxi Serif", "'Maxxi Serif', sans-serif"], ["Maxxi Serif Outline", "'Maxxi Serif Outline', sans-serif"], ["Nesdate October Ten", "'Nesdate October Ten', sans-serif"], 
      ["Phosphorus Bromide", "'Phosphorus Bromide', sans-serif"], ["Phosphorus Chloride", "'Phosphorus Chloride', sans-serif"], ["MKorsair", "'MKorsair', sans-serif"], 
      ["Phosphorus Hydride", "'Phosphorus Hydride', sans-serif"], ["Phosphorus Iodide", "'Phosphorus Iodide', sans-serif"], ["Phosphorus Oxide", "'Phosphorus Oxide', sans-serif"], 
      ["Phosphorus Selenide", "'Phosphorus Selenide', sans-serif"], ["Phosphorus Triselenide", "'Phosphorus Triselenide', sans-serif"], ["Antone", "'Antone', sans-serif"], 
      ["Phosphorus Tribromide", "'Phosphorus Tribromide', sans-serif"], ["Phosphorus Fluoride", "'Phosphorus Fluoride', sans-serif"], ["Winter_Sans", "'Winter_Sans', sans-serif"], 
      ["Phosphorus Dihydride", "'Phosphorus Dihydride', sans-serif"], ["Phosphorus Trichloride", "'Phosphorus Trichloride', sans-serif"], ["Phosphorus", "'Phosphorus', sans-serif"], 
      ["Phosphorus Sulphide", "'Phosphorus Sulphide', sans-serif"], ["The Real Font", "'The Real Font', sans-serif"], ["Parcel", "'Parcel', sans-serif"], 
      ["Virgula Vulgaris", "'Virgula Vulgaris', sans-serif"], ["Classy Coiffeur", "'Classy Coiffeur', sans-serif"], ["Prida65", "'Prida65', sans-serif"], 
      ["ZnikomitNo25", "'ZnikomitNo25', sans-serif"], ["Czesko", "'Czesko', sans-serif"], ["HarryPotter7", "'HarryPotter7', sans-serif"], ["Goulong", "'Goulong', sans-serif"],
      ["Bienetresocial", "'Bienetresocial', sans-serif"], ["Tribal Garamond", "'Tribal Garamond', sans-serif"], ["Apple Tree", "'Apple Tree', sans-serif"], 
      ["GalileoFLF", "'GalileoFLF', sans-serif"], ["Roman Flames", "'Roman Flames', sans-serif"], ["Merysha", "'Merysha', sans-serif"], ["Mob", "'Mob', sans-serif"], 
      ["Honeymoon Avenue Serif", "'Honeymoon Avenue Serif', sans-serif"], ["Domaine Display Narrow", "'Domaine Display Narrow', sans-serif"], ["Ultra", "'Ultra', sans-serif"], 
      ["VintageOne", "'VintageOne', sans-serif"], ["Durant", "'Durant', sans-serif"], ["Life LT Roman", "'Life LT Roman', sans-serif"], ["Notable", "'Notable', sans-serif"], 
      ["Kepler Std", "'Kepler Std', sans-serif"], ["Utopia Std", "'Utopia Std', sans-serif"], ["GalliardBldITC", "'GalliardBldITC', sans-serif"], 
      ["Benguiat Bk BT", "'Benguiat Bk BT', sans-serif"], ["Cheltenham LT", "'Cheltenham LT', sans-serif"], ["Nueva Std Extended", "'Nueva Std Extended', sans-serif"], 
      ["Nueva Std Regular", "'Nueva Std Regular', sans-serif"], ["Nueva Std", "'Nueva Std', sans-serif"], ["Nueva Std Condensed Italic", "'Nueva Std Condensed Italic', sans-serif"], 
      ["Nueva Std Extended Italic", "'Nueva Std Extended Italic', sans-serif"], ["Nueva Std Italic", "'Nueva Std Italic', sans-serif"], ["Sham", "'Sham', sans-serif"], 
      ["Nueva Std Light Extended", "'Nueva Std Light Extended', sans-serif"], ["WeekdaysRomanSlant", "'WeekdaysRomanSlant', sans-serif"], ["Bumpo", "'Bumpo', sans-serif"],
      ["Nueva Std Light", "'Nueva Std Light', sans-serif"], ["Nueva Std Light Extended Italic", "'Nueva Std Light Extended Italic', sans-serif"], 
      ["Nueva Std Light Italic", "'Nueva Std Light Italic', sans-serif"], ["Street Corner Slab Upper", "'Street Corner Slab Upper', sans-serif"],
      ["Nueva Std Bold Extended", "'Nueva Std Bold Extended', sans-serif"], ["Nueva Std Bold", "'Nueva Std Bold', sans-serif"], ["Muro", "'Muro', sans-serif"],
      ["Nueva Std Bold Condensed Italic", "'Nueva Std Bold Condensed Italic', sans-serif"], ["Lane Posh Light", "'Lane Posh Light', sans-serif"],
      ["Nueva Std Bold Extended Italic", "'Nueva Std Bold Extended Italic', sans-serif"], ["Nueva Std Bold Italic", "'Nueva Std Bold Italic', sans-serif"], 
      ["Bodoni", "'Bodoni', sans-serif"], ["Bodoni Twelve SC ITC TT", "'Bodoni Twelve SC ITC TT', sans-serif"], ["FrizQuadrata BT", "'FrizQuadrata BT', sans-serif"], 
      ["ITCCheltenham LT BookCond", "'ITCCheltenham LT BookCond', sans-serif"], ["Benguiat", "'Benguiat', sans-serif"], ["Friz Quadrata", "'Friz Quadrata', sans-serif"], 
      ["OFL Sorts Mill Goudy TT", "'OFL Sorts Mill Goudy TT', sans-serif"], ["Apex Serif Bold Italic", "'Apex Serif Bold Italic', sans-serif"], 
      ["Bree Serif Eb", "'Bree Serif Eb', sans-serif"], ["Bree Serif Sb", "'Bree Serif Sb', sans-serif"], ["Yokawerad", "'Yokawerad', sans-serif"], 
      ["Almendra", "'Almendra', sans-serif"], ["Almendra Display", "'Almendra Display', sans-serif"], ["Almendra SC", "'Almendra SC', sans-serif"], 
      ["Abril Fatface", "'Abril Fatface', sans-serif"], ["Bree Serif", "'Bree Serif', sans-serif"], ["Street Corner Slab", "'Street Corner Slab', sans-serif"], 
      ["Street Corner Slab Bold", "'Street Corner Slab Bold', sans-serif"], ["Street Corner Slab Extend", "'Street Corner Slab Extend', sans-serif"],  
      ["Street Corner Slab Narrower", "'Street Corner Slab Narrower', sans-serif"], ["Street Corner Slab Narrow", "'Street Corner Slab Narrow', sans-serif"], 
      ["Street Corner Slab SemiBold", "'Street Corner Slab SemiBold', sans-serif"], ["Street Corner Slab Upper Obl", "'Street Corner Slab Upper Obl', sans-serif"], 
      ["River Avenue", "'River Avenue', sans-serif"], ["Magnificent", "'Magnificent', sans-serif"], ["Ursa", "'Ursa', sans-serif"], ["UrsaSerif", "'UrsaSerif', sans-serif"],   
      ["Thurkle", "'Thurkle', sans-serif"], ["Saltstar", "'Saltstar', sans-serif"], ["The Blast", "'The Blast', sans-serif"], ["ResotE", "'ResotE', sans-serif"],
      ["Curbstone", "'Curbstone', sans-serif"], ["hotdogs", "'hotdogs', sans-serif"], ["PHANTOM", "'PHANTOM', sans-serif"], ["Goulong Bold", "'Goulong Bold', sans-serif"],
      ["Zacbel X", "'Zacbel X', sans-serif"], ["Zacbel X Medium", "'Zacbel X Medium', sans-serif"], ["Prometo Trial", "'Prometo Trial', sans-serif"], 
      ["X-Heighting", "'X-Heighting', sans-serif"], ["Letter Sketch", "'Letter Sketch', sans-serif"], ["Poetsen One", "'Poetsen One', sans-serif"], 
      ["SEIN BLUE", "'SEIN BLUE', sans-serif"], ["Pilo", "'Pilo', sans-serif"], ["ResotELavender", "'ResotELavender', sans-serif"], 
      ["Modern Machine", "'Modern Machine', sans-serif"], ["Fun Raiser-Hollow-Inverse", "'Fun Raiser-Hollow', sans-serif"], ["Fun Raiser", "'Fun Raiser', sans-serif"],
      ["SF Alien Encounters", "'SF Alien Encounters', sans-serif"], ["SF Alien Encounters Solid", "'SF Alien Encounters Solid', sans-serif"], 
      ["Gotham Condensed", "'Gotham Condensed', sans-serif"], ["Kabel Bd", "'Kabel Bd', sans-serif"], ["Fun Raiser-Light", "'Fun Raiser-Light', sans-serif"],
      ["ResotYg PERSONAL USE", "'ResotYg PERSONAL USE', sans-serif"], ["Republica Minor", "'Republica Minor', sans-serif"], ["DeconStruct", "'DeconStruct', sans-serif"], 
      ["Fun Raiser-Hollow-Inverse", "'Fun Raiser-Hollow-Inverse', sans-serif"], ["DeconStruct-Black", "'DeconStruct-Black', sans-serif"], 
      ["Fun Raiser-Inverse", "'Fun Raiser-Inverse', sans-serif"], ["AC Thermes", "'AC Thermes', sans-serif"], ["Cianjur On The Way", "'Cianjur On The Way', sans-serif"],
      ["FatSansRound", "'FatSansRound', sans-serif"], ["SF Buttacup Lettering Shaded", "'SF Buttacup Lettering Shaded', sans-serif"], 
      ["Goulong Bold Outline", "'Goulong Bold Outline', sans-serif"], ["Street Corner Slab Oblique", "'Street Corner Slab Oblique', sans-serif"],
      ["Goffik-Shadow", "'Goffik-Shadow', sans-serif"], ["Unability", "'Unability', sans-serif"], ["Klein Condensed Trial", "'Klein Condensed Trial', sans-serif"],
      ["Klein Trial", "'Klein Trial', sans-serif"], ["Klein Text Trial", "'Klein Text Trial', sans-serif"], ["El Boxeador", "'El Boxeador', sans-serif"], 
      ["SpotlightRomat", "'SpotlightRomat', sans-serif"], ["Casino Bar", "'Casino Bar', sans-serif"], ["DeconStruct-LightOblique", "'DeconStruct-LightOblique', sans-serif"], 
      ["Street Corner Slab HyperExtend", "'Street Corner Slab HyperExtend', sans-serif"], ["DeconStruct-BlackOblique", "'DeconStruct-BlackOblique', sans-serif"]
    ]
  end
end
