class GoogleFonts
  def full_list
    [
      ["ABeeZee", "'ABeeZee', sans-serif"],
      ["Abel", "'Abel', sans-serif"],
      ["Abhaya Libre", "'Abhaya Libre', serif"],
      ["Abril Fatface", "'Abril Fatface', display"],
      ["Aclonica", "'Aclonica', sans-serif"],
      ["Acme", "'Acme', sans-serif"],
      ["Actor", "'Actor', sans-serif"],
      ["Adamina", "'Adamina', serif"],
      ["Advent Pro", "'Advent Pro', sans-serif"],
      ["Aguafina Script", "'Aguafina Script', handwriting"],
      ["Akaya Kanadaka", "'Akaya Kanadaka', display"],
      ["Akaya Telivigala", "'Akaya Telivigala', display"],
      ["Akronim", "'Akronim', display"],
      ["Akshar", "'Akshar', sans-serif"],
      ["Aladin", "'Aladin', handwriting"],
      ["Alata", "'Alata', sans-serif"],
      ["Alatsi", "'Alatsi', sans-serif"],
      ["Albert Sans", "'Albert Sans', sans-serif"],
      ["Aldrich", "'Aldrich', sans-serif"],
      ["Alef", "'Alef', sans-serif"],
      ["Alegreya", "'Alegreya', serif"],
      ["Alegreya SC", "'Alegreya SC', serif"],
      ["Alegreya Sans", "'Alegreya Sans', sans-serif"],
      ["Alegreya Sans SC", "'Alegreya Sans SC', sans-serif"],
      ["Aleo", "'Aleo', serif"],
      ["Alex Brush", "'Alex Brush', handwriting"],
      ["Alfa Slab One", "'Alfa Slab One', display"],
      ["Alice", "'Alice', serif"],
      ["Alike", "'Alike', serif"],
      ["Alike Angular", "'Alike Angular', serif"],
      ["Allan", "'Allan', display"],
      ["Allerta", "'Allerta', sans-serif"],
      ["Allerta Stencil", "'Allerta Stencil', sans-serif"],
      ["Allison", "'Allison', handwriting"],
      ["Allura", "'Allura', handwriting"],
      ["Almarai", "'Almarai', sans-serif"],
      ["Almendra", "'Almendra', serif"],
      ["Almendra Display", "'Almendra Display', display"],
      ["Almendra SC", "'Almendra SC', serif"],
      ["Alumni Sans", "'Alumni Sans', sans-serif"],
      ["Alumni Sans Inline One", "'Alumni Sans Inline One', display"],
      ["Amarante", "'Amarante', display"],
      ["Amaranth", "'Amaranth', sans-serif"],
      ["Amatic SC", "'Amatic SC', handwriting"],
      ["Amethysta", "'Amethysta', serif"],
      ["Amiko", "'Amiko', sans-serif"],
      ["Amiri", "'Amiri', serif"],
      ["Amita", "'Amita', handwriting"],
      ["Anaheim", "'Anaheim', sans-serif"],
      ["Andada Pro", "'Andada Pro', serif"],
      ["Andika", "'Andika', sans-serif"],
      ["Anek Bangla", "'Anek Bangla', sans-serif"],
      ["Anek Devanagari", "'Anek Devanagari', sans-serif"],
      ["Anek Gujarati", "'Anek Gujarati', sans-serif"],
      ["Anek Gurmukhi", "'Anek Gurmukhi', sans-serif"],
      ["Anek Kannada", "'Anek Kannada', sans-serif"],
      ["Anek Latin", "'Anek Latin', sans-serif"],
      ["Anek Malayalam", "'Anek Malayalam', sans-serif"],
      ["Anek Odia", "'Anek Odia', sans-serif"],
      ["Anek Tamil", "'Anek Tamil', sans-serif"],
      ["Anek Telugu", "'Anek Telugu', sans-serif"],
      ["Angkor", "'Angkor', display"],
      ["Annie Use Your Telescope", "'Annie Use Your Telescope', handwriting"],
      ["Anonymous Pro", "'Anonymous Pro', monospace"],
      ["Antic", "'Antic', sans-serif"],
      ["Antic Didone", "'Antic Didone', serif"],
      ["Antic Slab", "'Antic Slab', serif"],
      ["Anton", "'Anton', sans-serif"],
      ["Antonio", "'Antonio', sans-serif"],
      ["Anybody", "'Anybody', display"],
      ["Arapey", "'Arapey', serif"],
      ["Arbutus", "'Arbutus', display"],
      ["Arbutus Slab", "'Arbutus Slab', serif"],
      ["Architects Daughter", "'Architects Daughter', handwriting"],
      ["Archivo", "'Archivo', sans-serif"],
      ["Archivo Black", "'Archivo Black', sans-serif"],
      ["Archivo Narrow", "'Archivo Narrow', sans-serif"],
      ["Are You Serious", "'Are You Serious', handwriting"],
      ["Aref Ruqaa", "'Aref Ruqaa', serif"],
      ["Arima", "'Arima', display"],
      ["Arima Madurai", "'Arima Madurai', display"],
      ["Arimo", "'Arimo', sans-serif"],
      ["Arizonia", "'Arizonia', handwriting"],
      ["Armata", "'Armata', sans-serif"],
      ["Arsenal", "'Arsenal', sans-serif"],
      ["Artifika", "'Artifika', serif"],
      ["Arvo", "'Arvo', serif"],
      ["Arya", "'Arya', sans-serif"],
      ["Asap", "'Asap', sans-serif"],
      ["Asap Condensed", "'Asap Condensed', sans-serif"],
      ["Asar", "'Asar', serif"],
      ["Asset", "'Asset', display"],
      ["Assistant", "'Assistant', sans-serif"],
      ["Astloch", "'Astloch', display"],
      ["Asul", "'Asul', sans-serif"],
      ["Athiti", "'Athiti', sans-serif"],
      ["Atkinson Hyperlegible", "'Atkinson Hyperlegible', sans-serif"],
      ["Atma", "'Atma', display"],
      ["Atomic Age", "'Atomic Age', display"],
      ["Aubrey", "'Aubrey', display"],
      ["Audiowide", "'Audiowide', display"],
      ["Autour One", "'Autour One', display"],
      ["Average", "'Average', serif"],
      ["Average Sans", "'Average Sans', sans-serif"],
      ["Averia Gruesa Libre", "'Averia Gruesa Libre', display"],
      ["Averia Libre", "'Averia Libre', display"],
      ["Averia Sans Libre", "'Averia Sans Libre', display"],
      ["Averia Serif Libre", "'Averia Serif Libre', display"],
      ["Azeret Mono", "'Azeret Mono', monospace"],
      ["B612", "'B612', sans-serif"],
      ["B612 Mono", "'B612 Mono', monospace"],
      ["BIZ UDGothic", "'BIZ UDGothic', sans-serif"],
      ["BIZ UDMincho", "'BIZ UDMincho', serif"],
      ["BIZ UDPGothic", "'BIZ UDPGothic', sans-serif"],
      ["BIZ UDPMincho", "'BIZ UDPMincho', serif"],
      ["Babylonica", "'Babylonica', handwriting"],
      ["Bad Script", "'Bad Script', handwriting"],
      ["Bahiana", "'Bahiana', display"],
      ["Bahianita", "'Bahianita', display"],
      ["Bai Jamjuree", "'Bai Jamjuree', sans-serif"],
      ["Bakbak One", "'Bakbak One', display"],
      ["Ballet", "'Ballet', handwriting"],
      ["Baloo 2", "'Baloo 2', display"],
      ["Baloo Bhai 2", "'Baloo Bhai 2', display"],
      ["Baloo Bhaijaan 2", "'Baloo Bhaijaan 2', display"],
      ["Baloo Bhaina 2", "'Baloo Bhaina 2', display"],
      ["Baloo Chettan 2", "'Baloo Chettan 2', display"],
      ["Baloo Da 2", "'Baloo Da 2', display"],
      ["Baloo Paaji 2", "'Baloo Paaji 2', display"],
      ["Baloo Tamma 2", "'Baloo Tamma 2', display"],
      ["Baloo Tammudu 2", "'Baloo Tammudu 2', display"],
      ["Baloo Thambi 2", "'Baloo Thambi 2', display"],
      ["Balsamiq Sans", "'Balsamiq Sans', display"],
      ["Balthazar", "'Balthazar', serif"],
      ["Bangers", "'Bangers', display"],
      ["Barlow", "'Barlow', sans-serif"],
      ["Barlow Condensed", "'Barlow Condensed', sans-serif"],
      ["Barlow Semi Condensed", "'Barlow Semi Condensed', sans-serif"],
      ["Barriecito", "'Barriecito', display"],
      ["Barrio", "'Barrio', display"],
      ["Basic", "'Basic', sans-serif"],
      ["Baskervville", "'Baskervville', serif"],
      ["Battambang", "'Battambang', display"],
      ["Baumans", "'Baumans', display"],
      ["Bayon", "'Bayon', sans-serif"],
      ["Be Vietnam Pro", "'Be Vietnam Pro', sans-serif"],
      ["Beau Rivage", "'Beau Rivage', handwriting"],
      ["Bebas Neue", "'Bebas Neue', display"],
      ["Belgrano", "'Belgrano', serif"],
      ["Bellefair", "'Bellefair', serif"],
      ["Belleza", "'Belleza', sans-serif"],
      ["Bellota", "'Bellota', display"],
      ["Bellota Text", "'Bellota Text', display"],
      ["BenchNine", "'BenchNine', sans-serif"],
      ["Benne", "'Benne', serif"],
      ["Bentham", "'Bentham', serif"],
      ["Berkshire Swash", "'Berkshire Swash', handwriting"],
      ["Besley", "'Besley', serif"],
      ["Beth Ellen", "'Beth Ellen', handwriting"],
      ["Bevan", "'Bevan', display"],
      ["BhuTuka Expanded One", "'BhuTuka Expanded One', display"],
      ["Big Shoulders Display", "'Big Shoulders Display', display"],
      ["Big Shoulders Inline Display", "'Big Shoulders Inline Display', display"],
      ["Big Shoulders Inline Text", "'Big Shoulders Inline Text', display"],
      ["Big Shoulders Stencil Display", "'Big Shoulders Stencil Display', display"],
      ["Big Shoulders Stencil Text", "'Big Shoulders Stencil Text', display"],
      ["Big Shoulders Text", "'Big Shoulders Text', display"],
      ["Bigelow Rules", "'Bigelow Rules', display"],
      ["Bigshot One", "'Bigshot One', display"],
      ["Bilbo", "'Bilbo', handwriting"],
      ["Bilbo Swash Caps", "'Bilbo Swash Caps', handwriting"],
      ["BioRhyme", "'BioRhyme', serif"],
      ["BioRhyme Expanded", "'BioRhyme Expanded', serif"],
      ["Birthstone", "'Birthstone', handwriting"],
      ["Birthstone Bounce", "'Birthstone Bounce', handwriting"],
      ["Biryani", "'Biryani', sans-serif"],
      ["Bitter", "'Bitter', serif"],
      ["Black And White Picture", "'Black And White Picture', sans-serif"],
      ["Black Han Sans", "'Black Han Sans', sans-serif"],
      ["Black Ops One", "'Black Ops One', display"],
      ["Blaka", "'Blaka', display"],
      ["Blaka Hollow", "'Blaka Hollow', display"],
      ["Blinker", "'Blinker', sans-serif"],
      ["Bodoni Moda", "'Bodoni Moda', serif"],
      ["Bokor", "'Bokor', display"],
      ["Bona Nova", "'Bona Nova', serif"],
      ["Bonbon", "'Bonbon', handwriting"],
      ["Bonheur Royale", "'Bonheur Royale', handwriting"],
      ["Boogaloo", "'Boogaloo', display"],
      ["Bowlby One", "'Bowlby One', display"],
      ["Bowlby One SC", "'Bowlby One SC', display"],
      ["Brawler", "'Brawler', serif"],
      ["Bree Serif", "'Bree Serif', serif"],
      ["Brygada 1918", "'Brygada 1918', serif"],
      ["Bubblegum Sans", "'Bubblegum Sans', display"],
      ["Bubbler One", "'Bubbler One', sans-serif"],
      ["Buda", "'Buda', display"],
      ["Buenard", "'Buenard', serif"],
      ["Bungee", "'Bungee', display"],
      ["Bungee Hairline", "'Bungee Hairline', display"],
      ["Bungee Inline", "'Bungee Inline', display"],
      ["Bungee Outline", "'Bungee Outline', display"],
      ["Bungee Shade", "'Bungee Shade', display"],
      ["Butcherman", "'Butcherman', display"],
      ["Butterfly Kids", "'Butterfly Kids', handwriting"],
      ["Cabin", "'Cabin', sans-serif"],
      ["Cabin Condensed", "'Cabin Condensed', sans-serif"],
      ["Cabin Sketch", "'Cabin Sketch', display"],
      ["Caesar Dressing", "'Caesar Dressing', display"],
      ["Cagliostro", "'Cagliostro', sans-serif"],
      ["Cairo", "'Cairo', sans-serif"],
      ["Caladea", "'Caladea', serif"],
      ["Calistoga", "'Calistoga', display"],
      ["Calligraffitti", "'Calligraffitti', handwriting"],
      ["Cambay", "'Cambay', sans-serif"],
      ["Cambo", "'Cambo', serif"],
      ["Candal", "'Candal', sans-serif"],
      ["Cantarell", "'Cantarell', sans-serif"],
      ["Cantata One", "'Cantata One', serif"],
      ["Cantora One", "'Cantora One', sans-serif"],
      ["Capriola", "'Capriola', sans-serif"],
      ["Caramel", "'Caramel', handwriting"],
      ["Carattere", "'Carattere', handwriting"],
      ["Cardo", "'Cardo', serif"],
      ["Carme", "'Carme', sans-serif"],
      ["Carrois Gothic", "'Carrois Gothic', sans-serif"],
      ["Carrois Gothic SC", "'Carrois Gothic SC', sans-serif"],
      ["Carter One", "'Carter One', display"],
      ["Castoro", "'Castoro', serif"],
      ["Catamaran", "'Catamaran', sans-serif"],
      ["Caudex", "'Caudex', serif"],
      ["Caveat", "'Caveat', handwriting"],
      ["Caveat Brush", "'Caveat Brush', handwriting"],
      ["Cedarville Cursive", "'Cedarville Cursive', handwriting"],
      ["Ceviche One", "'Ceviche One', display"],
      ["Chakra Petch", "'Chakra Petch', sans-serif"],
      ["Changa", "'Changa', sans-serif"],
      ["Changa One", "'Changa One', display"],
      ["Chango", "'Chango', display"],
      ["Charis SIL", "'Charis SIL', serif"],
      ["Charm", "'Charm', handwriting"],
      ["Charmonman", "'Charmonman', handwriting"],
      ["Chathura", "'Chathura', sans-serif"],
      ["Chau Philomene One", "'Chau Philomene One', sans-serif"],
      ["Chela One", "'Chela One', display"],
      ["Chelsea Market", "'Chelsea Market', display"],
      ["Chenla", "'Chenla', display"],
      ["Cherish", "'Cherish', handwriting"],
      ["Cherry Cream Soda", "'Cherry Cream Soda', display"],
      ["Cherry Swash", "'Cherry Swash', display"],
      ["Chewy", "'Chewy', display"],
      ["Chicle", "'Chicle', display"],
      ["Chilanka", "'Chilanka', handwriting"],
      ["Chivo", "'Chivo', sans-serif"],
      ["Chonburi", "'Chonburi', display"],
      ["Cinzel", "'Cinzel', serif"],
      ["Cinzel Decorative", "'Cinzel Decorative', display"],
      ["Clicker Script", "'Clicker Script', handwriting"],
      ["Coda", "'Coda', display"],
      ["Coda Caption", "'Coda Caption', sans-serif"],
      ["Codystar", "'Codystar', display"],
      ["Coiny", "'Coiny', display"],
      ["Combo", "'Combo', display"],
      ["Comfortaa", "'Comfortaa', display"],
      ["Comforter", "'Comforter', handwriting"],
      ["Comforter Brush", "'Comforter Brush', handwriting"],
      ["Comic Neue", "'Comic Neue', handwriting"],
      ["Coming Soon", "'Coming Soon', handwriting"],
      ["Commissioner", "'Commissioner', sans-serif"],
      ["Concert One", "'Concert One', display"],
      ["Condiment", "'Condiment', handwriting"],
      ["Content", "'Content', display"],
      ["Contrail One", "'Contrail One', display"],
      ["Convergence", "'Convergence', sans-serif"],
      ["Cookie", "'Cookie', handwriting"],
      ["Copse", "'Copse', serif"],
      ["Corben", "'Corben', display"],
      ["Corinthia", "'Corinthia', handwriting"],
      ["Cormorant", "'Cormorant', serif"],
      ["Cormorant Garamond", "'Cormorant Garamond', serif"],
      ["Cormorant Infant", "'Cormorant Infant', serif"],
      ["Cormorant SC", "'Cormorant SC', serif"],
      ["Cormorant Unicase", "'Cormorant Unicase', serif"],
      ["Cormorant Upright", "'Cormorant Upright', serif"],
      ["Courgette", "'Courgette', handwriting"],
      ["Courier Prime", "'Courier Prime', monospace"],
      ["Cousine", "'Cousine', monospace"],
      ["Coustard", "'Coustard', serif"],
      ["Covered By Your Grace", "'Covered By Your Grace', handwriting"],
      ["Crafty Girls", "'Crafty Girls', handwriting"],
      ["Creepster", "'Creepster', display"],
      ["Crete Round", "'Crete Round', serif"],
      ["Crimson Pro", "'Crimson Pro', serif"],
      ["Crimson Text", "'Crimson Text', serif"],
      ["Croissant One", "'Croissant One', display"],
      ["Crushed", "'Crushed', display"],
      ["Cuprum", "'Cuprum', sans-serif"],
      ["Cute Font", "'Cute Font', display"],
      ["Cutive", "'Cutive', serif"],
      ["Cutive Mono", "'Cutive Mono', monospace"],
      ["DM Mono", "'DM Mono', monospace"],
      ["DM Sans", "'DM Sans', sans-serif"],
      ["DM Serif Display", "'DM Serif Display', serif"],
      ["DM Serif Text", "'DM Serif Text', serif"],
      ["Damion", "'Damion', handwriting"],
      ["Dancing Script", "'Dancing Script', handwriting"],
      ["Dangrek", "'Dangrek', display"],
      ["Darker Grotesque", "'Darker Grotesque', sans-serif"],
      ["David Libre", "'David Libre', serif"],
      ["Dawning of a New Day", "'Dawning of a New Day', handwriting"],
      ["Days One", "'Days One', sans-serif"],
      ["Dekko", "'Dekko', handwriting"],
      ["Dela Gothic One", "'Dela Gothic One', display"],
      ["Delius", "'Delius', handwriting"],
      ["Delius Swash Caps", "'Delius Swash Caps', handwriting"],
      ["Delius Unicase", "'Delius Unicase', handwriting"],
      ["Della Respira", "'Della Respira', serif"],
      ["Denk One", "'Denk One', sans-serif"],
      ["Devonshire", "'Devonshire', handwriting"],
      ["Dhurjati", "'Dhurjati', sans-serif"],
      ["Didact Gothic", "'Didact Gothic', sans-serif"],
      ["Diplomata", "'Diplomata', display"],
      ["Diplomata SC", "'Diplomata SC', display"],
      ["Do Hyeon", "'Do Hyeon', sans-serif"],
      ["Dokdo", "'Dokdo', handwriting"],
      ["Domine", "'Domine', serif"],
      ["Donegal One", "'Donegal One', serif"],
      ["Dongle", "'Dongle', sans-serif"],
      ["Doppio One", "'Doppio One', sans-serif"],
      ["Dorsa", "'Dorsa', sans-serif"],
      ["Dosis", "'Dosis', sans-serif"],
      ["DotGothic16", "'DotGothic16', sans-serif"],
      ["Dr Sugiyama", "'Dr Sugiyama', handwriting"],
      ["Duru Sans", "'Duru Sans', sans-serif"],
      ["Dynalight", "'Dynalight', display"],
      ["EB Garamond", "'EB Garamond', serif"],
      ["Eagle Lake", "'Eagle Lake', handwriting"],
      ["East Sea Dokdo", "'East Sea Dokdo', handwriting"],
      ["Eater", "'Eater', display"],
      ["Economica", "'Economica', sans-serif"],
      ["Eczar", "'Eczar', serif"],
      ["Edu NSW ACT Foundation", "'Edu NSW ACT Foundation', handwriting"],
      ["Edu QLD Beginner", "'Edu QLD Beginner', handwriting"],
      ["Edu SA Beginner", "'Edu SA Beginner', handwriting"],
      ["Edu TAS Beginner", "'Edu TAS Beginner', handwriting"],
      ["Edu VIC WA NT Beginner", "'Edu VIC WA NT Beginner', handwriting"],
      ["El Messiri", "'El Messiri', sans-serif"],
      ["Electrolize", "'Electrolize', sans-serif"],
      ["Elsie", "'Elsie', display"],
      ["Elsie Swash Caps", "'Elsie Swash Caps', display"],
      ["Emblema One", "'Emblema One', display"],
      ["Emilys Candy", "'Emilys Candy', display"],
      ["Encode Sans", "'Encode Sans', sans-serif"],
      ["Encode Sans Condensed", "'Encode Sans Condensed', sans-serif"],
      ["Encode Sans Expanded", "'Encode Sans Expanded', sans-serif"],
      ["Encode Sans SC", "'Encode Sans SC', sans-serif"],
      ["Encode Sans Semi Condensed", "'Encode Sans Semi Condensed', sans-serif"],
      ["Encode Sans Semi Expanded", "'Encode Sans Semi Expanded', sans-serif"],
      ["Engagement", "'Engagement', handwriting"],
      ["Englebert", "'Englebert', sans-serif"],
      ["Enriqueta", "'Enriqueta', serif"],
      ["Ephesis", "'Ephesis', handwriting"],
      ["Epilogue", "'Epilogue', sans-serif"],
      ["Erica One", "'Erica One', display"],
      ["Esteban", "'Esteban', serif"],
      ["Estonia", "'Estonia', handwriting"],
      ["Euphoria Script", "'Euphoria Script', handwriting"],
      ["Ewert", "'Ewert', display"],
      ["Exo", "'Exo', sans-serif"],
      ["Exo 2", "'Exo 2', sans-serif"],
      ["Expletus Sans", "'Expletus Sans', display"],
      ["Explora", "'Explora', handwriting"],
      ["Fahkwang", "'Fahkwang', sans-serif"],
      ["Familjen Grotesk", "'Familjen Grotesk', sans-serif"],
      ["Fanwood Text", "'Fanwood Text', serif"],
      ["Farro", "'Farro', sans-serif"],
      ["Farsan", "'Farsan', display"],
      ["Fascinate", "'Fascinate', display"],
      ["Fascinate Inline", "'Fascinate Inline', display"],
      ["Faster One", "'Faster One', display"],
      ["Fasthand", "'Fasthand', display"],
      ["Fauna One", "'Fauna One', serif"],
      ["Faustina", "'Faustina', serif"],
      ["Federant", "'Federant', display"],
      ["Federo", "'Federo', sans-serif"],
      ["Felipa", "'Felipa', handwriting"],
      ["Fenix", "'Fenix', serif"],
      ["Festive", "'Festive', handwriting"],
      ["Finger Paint", "'Finger Paint', display"],
      ["Finlandica", "'Finlandica', sans-serif"],
      ["Fira Code", "'Fira Code', monospace"],
      ["Fira Mono", "'Fira Mono', monospace"],
      ["Fira Sans", "'Fira Sans', sans-serif"],
      ["Fira Sans Condensed", "'Fira Sans Condensed', sans-serif"],
      ["Fira Sans Extra Condensed", "'Fira Sans Extra Condensed', sans-serif"],
      ["Fjalla One", "'Fjalla One', sans-serif"],
      ["Fjord One", "'Fjord One', serif"],
      ["Flamenco", "'Flamenco', display"],
      ["Flavors", "'Flavors', display"],
      ["Fleur De Leah", "'Fleur De Leah', handwriting"],
      ["Flow Block", "'Flow Block', display"],
      ["Flow Circular", "'Flow Circular', display"],
      ["Flow Rounded", "'Flow Rounded', display"],
      ["Fondamento", "'Fondamento', handwriting"],
      ["Fontdiner Swanky", "'Fontdiner Swanky', display"],
      ["Forum", "'Forum', display"],
      ["Francois One", "'Francois One', sans-serif"],
      ["Frank Ruhl Libre", "'Frank Ruhl Libre', serif"],
      ["Fraunces", "'Fraunces', serif"],
      ["Freckle Face", "'Freckle Face', display"],
      ["Fredericka the Great", "'Fredericka the Great', display"],
      ["Fredoka", "'Fredoka', sans-serif"],
      ["Fredoka One", "'Fredoka One', display"],
      ["Freehand", "'Freehand', display"],
      ["Fresca", "'Fresca', sans-serif"],
      ["Frijole", "'Frijole', display"],
      ["Fruktur", "'Fruktur', display"],
      ["Fugaz One", "'Fugaz One', display"],
      ["Fuggles", "'Fuggles', handwriting"],
      ["Fuzzy Bubbles", "'Fuzzy Bubbles', handwriting"],
      ["GFS Didot", "'GFS Didot', serif"],
      ["GFS Neohellenic", "'GFS Neohellenic', sans-serif"],
      ["Gabriela", "'Gabriela', serif"],
      ["Gaegu", "'Gaegu', handwriting"],
      ["Gafata", "'Gafata', sans-serif"],
      ["Galada", "'Galada', display"],
      ["Galdeano", "'Galdeano', sans-serif"],
      ["Galindo", "'Galindo', display"],
      ["Gamja Flower", "'Gamja Flower', handwriting"],
      ["Gantari", "'Gantari', sans-serif"],
      ["Gayathri", "'Gayathri', sans-serif"],
      ["Gelasio", "'Gelasio', serif"],
      ["Gemunu Libre", "'Gemunu Libre', sans-serif"],
      ["Genos", "'Genos', sans-serif"],
      ["Gentium Book Basic", "'Gentium Book Basic', serif"],
      ["Gentium Book Plus", "'Gentium Book Plus', serif"],
      ["Gentium Plus", "'Gentium Plus', serif"],
      ["Geo", "'Geo', sans-serif"],
      ["Georama", "'Georama', sans-serif"],
      ["Geostar", "'Geostar', display"],
      ["Geostar Fill", "'Geostar Fill', display"],
      ["Germania One", "'Germania One', display"],
      ["Gideon Roman", "'Gideon Roman', display"],
      ["Gidugu", "'Gidugu', sans-serif"],
      ["Gilda Display", "'Gilda Display', serif"],
      ["Girassol", "'Girassol', display"],
      ["Give You Glory", "'Give You Glory', handwriting"],
      ["Glass Antiqua", "'Glass Antiqua', display"],
      ["Glegoo", "'Glegoo', serif"],
      ["Gloria Hallelujah", "'Gloria Hallelujah', handwriting"],
      ["Glory", "'Glory', sans-serif"],
      ["Gluten", "'Gluten', display"],
      ["Goblin One", "'Goblin One', display"],
      ["Gochi Hand", "'Gochi Hand', handwriting"],
      ["Goldman", "'Goldman', display"],
      ["Gorditas", "'Gorditas', display"],
      ["Gothic A1", "'Gothic A1', sans-serif"],
      ["Gotu", "'Gotu', sans-serif"],
      ["Goudy Bookletter 1911", "'Goudy Bookletter 1911', serif"],
      ["Gowun Batang", "'Gowun Batang', serif"],
      ["Gowun Dodum", "'Gowun Dodum', sans-serif"],
      ["Graduate", "'Graduate', display"],
      ["Grand Hotel", "'Grand Hotel', handwriting"],
      ["Grandstander", "'Grandstander', display"],
      ["Grape Nuts", "'Grape Nuts', handwriting"],
      ["Gravitas One", "'Gravitas One', display"],
      ["Great Vibes", "'Great Vibes', handwriting"],
      ["Grechen Fuemen", "'Grechen Fuemen', handwriting"],
      ["Grenze", "'Grenze', serif"],
      ["Grenze Gotisch", "'Grenze Gotisch', display"],
      ["Grey Qo", "'Grey Qo', handwriting"],
      ["Griffy", "'Griffy', display"],
      ["Gruppo", "'Gruppo', display"],
      ["Gudea", "'Gudea', sans-serif"],
      ["Gugi", "'Gugi', display"],
      ["Gulzar", "'Gulzar', serif"],
      ["Gupter", "'Gupter', serif"],
      ["Gurajada", "'Gurajada', serif"],
      ["Gwendolyn", "'Gwendolyn', handwriting"],
      ["Habibi", "'Habibi', serif"],
      ["Hachi Maru Pop", "'Hachi Maru Pop', handwriting"],
      ["Hahmlet", "'Hahmlet', serif"],
      ["Halant", "'Halant', serif"],
      ["Hammersmith One", "'Hammersmith One', sans-serif"],
      ["Hanalei", "'Hanalei', display"],
      ["Hanalei Fill", "'Hanalei Fill', display"],
      ["Handlee", "'Handlee', handwriting"],
      ["Hanuman", "'Hanuman', serif"],
      ["Happy Monkey", "'Happy Monkey', display"],
      ["Harmattan", "'Harmattan', sans-serif"],
      ["Headland One", "'Headland One', serif"],
      ["Heebo", "'Heebo', sans-serif"],
      ["Henny Penny", "'Henny Penny', display"],
      ["Hepta Slab", "'Hepta Slab', serif"],
      ["Herr Von Muellerhoff", "'Herr Von Muellerhoff', handwriting"],
      ["Hi Melody", "'Hi Melody', handwriting"],
      ["Hina Mincho", "'Hina Mincho', serif"],
      ["Hind", "'Hind', sans-serif"],
      ["Hind Guntur", "'Hind Guntur', sans-serif"],
      ["Hind Madurai", "'Hind Madurai', sans-serif"],
      ["Hind Siliguri", "'Hind Siliguri', sans-serif"],
      ["Hind Vadodara", "'Hind Vadodara', sans-serif"],
      ["Holtwood One SC", "'Holtwood One SC', serif"],
      ["Homemade Apple", "'Homemade Apple', handwriting"],
      ["Homenaje", "'Homenaje', sans-serif"],
      ["Hubballi", "'Hubballi', display"],
      ["Hurricane", "'Hurricane', handwriting"],
      ["IBM Plex Mono", "'IBM Plex Mono', monospace"],
      ["IBM Plex Sans", "'IBM Plex Sans', sans-serif"],
      ["IBM Plex Sans Arabic", "'IBM Plex Sans Arabic', sans-serif"],
      ["IBM Plex Sans Condensed", "'IBM Plex Sans Condensed', sans-serif"],
      ["IBM Plex Sans Devanagari", "'IBM Plex Sans Devanagari', sans-serif"],
      ["IBM Plex Sans Hebrew", "'IBM Plex Sans Hebrew', sans-serif"],
      ["IBM Plex Sans KR", "'IBM Plex Sans KR', sans-serif"],
      ["IBM Plex Sans Thai", "'IBM Plex Sans Thai', sans-serif"],
      ["IBM Plex Sans Thai Looped", "'IBM Plex Sans Thai Looped', sans-serif"],
      ["IBM Plex Serif", "'IBM Plex Serif', serif"],
      ["IM Fell DW Pica", "'IM Fell DW Pica', serif"],
      ["IM Fell DW Pica SC", "'IM Fell DW Pica SC', serif"],
      ["IM Fell Double Pica", "'IM Fell Double Pica', serif"],
      ["IM Fell Double Pica SC", "'IM Fell Double Pica SC', serif"],
      ["IM Fell English", "'IM Fell English', serif"],
      ["IM Fell English SC", "'IM Fell English SC', serif"],
      ["IM Fell French Canon", "'IM Fell French Canon', serif"],
      ["IM Fell French Canon SC", "'IM Fell French Canon SC', serif"],
      ["IM Fell Great Primer", "'IM Fell Great Primer', serif"],
      ["IM Fell Great Primer SC", "'IM Fell Great Primer SC', serif"],
      ["Ibarra Real Nova", "'Ibarra Real Nova', serif"],
      ["Iceberg", "'Iceberg', display"],
      ["Iceland", "'Iceland', display"],
      ["Imbue", "'Imbue', serif"],
      ["Imperial Script", "'Imperial Script', handwriting"],
      ["Imprima", "'Imprima', sans-serif"],
      ["Inconsolata", "'Inconsolata', monospace"],
      ["Inder", "'Inder', sans-serif"],
      ["Indie Flower", "'Indie Flower', handwriting"],
      ["Ingrid Darling", "'Ingrid Darling', handwriting"],
      ["Inika", "'Inika', serif"],
      ["Inknut Antiqua", "'Inknut Antiqua', serif"],
      ["Inria Sans", "'Inria Sans', sans-serif"],
      ["Inria Serif", "'Inria Serif', serif"],
      ["Inspiration", "'Inspiration', handwriting"],
      ["Inter", "'Inter', sans-serif"],
      ["Irish Grover", "'Irish Grover', display"],
      ["Island Moments", "'Island Moments', handwriting"],
      ["Istok Web", "'Istok Web', sans-serif"],
      ["Italiana", "'Italiana', serif"],
      ["Italianno", "'Italianno', handwriting"],
      ["Itim", "'Itim', handwriting"],
      ["Jacques Francois", "'Jacques Francois', serif"],
      ["Jacques Francois Shadow", "'Jacques Francois Shadow', display"],
      ["Jaldi", "'Jaldi', sans-serif"],
      ["JetBrains Mono", "'JetBrains Mono', monospace"],
      ["Jim Nightshade", "'Jim Nightshade', handwriting"],
      ["Joan", "'Joan', serif"],
      ["Jockey One", "'Jockey One', sans-serif"],
      ["Jolly Lodger", "'Jolly Lodger', display"],
      ["Jomhuria", "'Jomhuria', display"],
      ["Jomolhari", "'Jomolhari', serif"],
      ["Josefin Sans", "'Josefin Sans', sans-serif"],
      ["Josefin Slab", "'Josefin Slab', serif"],
      ["Jost", "'Jost', sans-serif"],
      ["Joti One", "'Joti One', display"],
      ["Jua", "'Jua', sans-serif"],
      ["Judson", "'Judson', serif"],
      ["Julee", "'Julee', handwriting"],
      ["Julius Sans One", "'Julius Sans One', sans-serif"],
      ["Junge", "'Junge', serif"],
      ["Jura", "'Jura', sans-serif"],
      ["Just Another Hand", "'Just Another Hand', handwriting"],
      ["Just Me Again Down Here", "'Just Me Again Down Here', handwriting"],
      ["K2D", "'K2D', sans-serif"],
      ["Kadwa", "'Kadwa', serif"],
      ["Kaisei Decol", "'Kaisei Decol', serif"],
      ["Kaisei HarunoUmi", "'Kaisei HarunoUmi', serif"],
      ["Kaisei Opti", "'Kaisei Opti', serif"],
      ["Kaisei Tokumin", "'Kaisei Tokumin', serif"],
      ["Kalam", "'Kalam', handwriting"],
      ["Kameron", "'Kameron', serif"],
      ["Kanit", "'Kanit', sans-serif"],
      ["Kantumruy", "'Kantumruy', sans-serif"],
      ["Kantumruy Pro", "'Kantumruy Pro', sans-serif"],
      ["Karantina", "'Karantina', display"],
      ["Karla", "'Karla', sans-serif"],
      ["Karma", "'Karma', serif"],
      ["Katibeh", "'Katibeh', display"],
      ["Kaushan Script", "'Kaushan Script', handwriting"],
      ["Kavivanar", "'Kavivanar', handwriting"],
      ["Kavoon", "'Kavoon', display"],
      ["Kdam Thmor Pro", "'Kdam Thmor Pro', sans-serif"],
      ["Keania One", "'Keania One', display"],
      ["Kelly Slab", "'Kelly Slab', display"],
      ["Kenia", "'Kenia', display"],
      ["Khand", "'Khand', sans-serif"],
      ["Khmer", "'Khmer', display"],
      ["Khula", "'Khula', sans-serif"],
      ["Kings", "'Kings', handwriting"],
      ["Kirang Haerang", "'Kirang Haerang', display"],
      ["Kite One", "'Kite One', sans-serif"],
      ["Kiwi Maru", "'Kiwi Maru', serif"],
      ["Klee One", "'Klee One', handwriting"],
      ["Knewave", "'Knewave', display"],
      ["KoHo", "'KoHo', sans-serif"],
      ["Kodchasan", "'Kodchasan', sans-serif"],
      ["Koh Santepheap", "'Koh Santepheap', display"],
      ["Kolker Brush", "'Kolker Brush', handwriting"],
      ["Kosugi", "'Kosugi', sans-serif"],
      ["Kosugi Maru", "'Kosugi Maru', sans-serif"],
      ["Kotta One", "'Kotta One', serif"],
      ["Koulen", "'Koulen', display"],
      ["Kranky", "'Kranky', display"],
      ["Kreon", "'Kreon', serif"],
      ["Kristi", "'Kristi', handwriting"],
      ["Krona One", "'Krona One', sans-serif"],
      ["Krub", "'Krub', sans-serif"],
      ["Kufam", "'Kufam', sans-serif"],
      ["Kulim Park", "'Kulim Park', sans-serif"],
      ["Kumar One", "'Kumar One', display"],
      ["Kumar One Outline", "'Kumar One Outline', display"],
      ["Kumbh Sans", "'Kumbh Sans', sans-serif"],
      ["Kurale", "'Kurale', serif"],
      ["La Belle Aurore", "'La Belle Aurore', handwriting"],
      ["Lacquer", "'Lacquer', display"],
      ["Laila", "'Laila', sans-serif"],
      ["Lakki Reddy", "'Lakki Reddy', handwriting"],
      ["Lalezar", "'Lalezar', display"],
      ["Lancelot", "'Lancelot', display"],
      ["Langar", "'Langar', display"],
      ["Lateef", "'Lateef', handwriting"],
      ["Lato", "'Lato', sans-serif"],
      ["Lavishly Yours", "'Lavishly Yours', handwriting"],
      ["League Gothic", "'League Gothic', sans-serif"],
      ["League Script", "'League Script', handwriting"],
      ["League Spartan", "'League Spartan', sans-serif"],
      ["Leckerli One", "'Leckerli One', handwriting"],
      ["Ledger", "'Ledger', serif"],
      ["Lekton", "'Lekton', sans-serif"],
      ["Lemon", "'Lemon', display"],
      ["Lemonada", "'Lemonada', display"],
      ["Lexend", "'Lexend', sans-serif"],
      ["Lexend Deca", "'Lexend Deca', sans-serif"],
      ["Lexend Exa", "'Lexend Exa', sans-serif"],
      ["Lexend Giga", "'Lexend Giga', sans-serif"],
      ["Lexend Mega", "'Lexend Mega', sans-serif"],
      ["Lexend Peta", "'Lexend Peta', sans-serif"],
      ["Lexend Tera", "'Lexend Tera', sans-serif"],
      ["Lexend Zetta", "'Lexend Zetta', sans-serif"],
      ["Libre Barcode 128", "'Libre Barcode 128', display"],
      ["Libre Barcode 128 Text", "'Libre Barcode 128 Text', display"],
      ["Libre Barcode 39", "'Libre Barcode 39', display"],
      ["Libre Barcode 39 Extended", "'Libre Barcode 39 Extended', display"],
      ["Libre Barcode 39 Extended Text", "'Libre Barcode 39 Extended Text', display"],
      ["Libre Barcode 39 Text", "'Libre Barcode 39 Text', display"],
      ["Libre Barcode EAN13 Text", "'Libre Barcode EAN13 Text', display"],
      ["Libre Baskerville", "'Libre Baskerville', serif"],
      ["Libre Bodoni", "'Libre Bodoni', serif"],
      ["Libre Caslon Display", "'Libre Caslon Display', serif"],
      ["Libre Caslon Text", "'Libre Caslon Text', serif"],
      ["Libre Franklin", "'Libre Franklin', sans-serif"],
      ["Licorice", "'Licorice', handwriting"],
      ["Life Savers", "'Life Savers', display"],
      ["Lilita One", "'Lilita One', display"],
      ["Lily Script One", "'Lily Script One', display"],
      ["Limelight", "'Limelight', display"],
      ["Linden Hill", "'Linden Hill', serif"],
      ["Literata", "'Literata', serif"],
      ["Liu Jian Mao Cao", "'Liu Jian Mao Cao', handwriting"],
      ["Livvic", "'Livvic', sans-serif"],
      ["Lobster", "'Lobster', display"],
      ["Lobster Two", "'Lobster Two', display"],
      ["Londrina Outline", "'Londrina Outline', display"],
      ["Londrina Shadow", "'Londrina Shadow', display"],
      ["Londrina Sketch", "'Londrina Sketch', display"],
      ["Londrina Solid", "'Londrina Solid', display"],
      ["Long Cang", "'Long Cang', handwriting"],
      ["Lora", "'Lora', serif"],
      ["Love Light", "'Love Light', handwriting"],
      ["Love Ya Like A Sister", "'Love Ya Like A Sister', display"],
      ["Loved by the King", "'Loved by the King', handwriting"],
      ["Lovers Quarrel", "'Lovers Quarrel', handwriting"],
      ["Luckiest Guy", "'Luckiest Guy', display"],
      ["Lusitana", "'Lusitana', serif"],
      ["Lustria", "'Lustria', serif"],
      ["Luxurious Roman", "'Luxurious Roman', display"],
      ["Luxurious Script", "'Luxurious Script', handwriting"],
      ["M PLUS 1", "'M PLUS 1', sans-serif"],
      ["M PLUS 1 Code", "'M PLUS 1 Code', sans-serif"],
      ["M PLUS 1p", "'M PLUS 1p', sans-serif"],
      ["M PLUS 2", "'M PLUS 2', sans-serif"],
      ["M PLUS Code Latin", "'M PLUS Code Latin', sans-serif"],
      ["M PLUS Rounded 1c", "'M PLUS Rounded 1c', sans-serif"],
      ["Ma Shan Zheng", "'Ma Shan Zheng', handwriting"],
      ["Macondo", "'Macondo', display"],
      ["Macondo Swash Caps", "'Macondo Swash Caps', display"],
      ["Mada", "'Mada', sans-serif"],
      ["Magra", "'Magra', sans-serif"],
      ["Maiden Orange", "'Maiden Orange', display"],
      ["Maitree", "'Maitree', serif"],
      ["Major Mono Display", "'Major Mono Display', monospace"],
      ["Mako", "'Mako', sans-serif"],
      ["Mali", "'Mali', handwriting"],
      ["Mallanna", "'Mallanna', sans-serif"],
      ["Mandali", "'Mandali', sans-serif"],
      ["Manjari", "'Manjari', sans-serif"],
      ["Manrope", "'Manrope', sans-serif"],
      ["Mansalva", "'Mansalva', handwriting"],
      ["Manuale", "'Manuale', serif"],
      ["Marcellus", "'Marcellus', serif"],
      ["Marcellus SC", "'Marcellus SC', serif"],
      ["Marck Script", "'Marck Script', handwriting"],
      ["Margarine", "'Margarine', display"],
      ["Markazi Text", "'Markazi Text', serif"],
      ["Marko One", "'Marko One', serif"],
      ["Marmelad", "'Marmelad', sans-serif"],
      ["Martel", "'Martel', serif"],
      ["Martel Sans", "'Martel Sans', sans-serif"],
      ["Marvel", "'Marvel', sans-serif"],
      ["Mate", "'Mate', serif"],
      ["Mate SC", "'Mate SC', serif"],
      ["Maven Pro", "'Maven Pro', sans-serif"],
      ["McLaren", "'McLaren', display"],
      ["Mea Culpa", "'Mea Culpa', handwriting"],
      ["Meddon", "'Meddon', handwriting"],
      ["MedievalSharp", "'MedievalSharp', display"],
      ["Medula One", "'Medula One', display"],
      ["Meera Inimai", "'Meera Inimai', sans-serif"],
      ["Megrim", "'Megrim', display"],
      ["Meie Script", "'Meie Script', handwriting"],
      ["Meow Script", "'Meow Script', handwriting"],
      ["Merienda", "'Merienda', handwriting"],
      ["Merienda One", "'Merienda One', handwriting"],
      ["Merriweather", "'Merriweather', serif"],
      ["Merriweather Sans", "'Merriweather Sans', sans-serif"],
      ["Metal", "'Metal', display"],
      ["Metal Mania", "'Metal Mania', display"],
      ["Metamorphous", "'Metamorphous', display"],
      ["Metrophobic", "'Metrophobic', sans-serif"],
      ["Michroma", "'Michroma', sans-serif"],
      ["Milonga", "'Milonga', display"],
      ["Miltonian", "'Miltonian', display"],
      ["Miltonian Tattoo", "'Miltonian Tattoo', display"],
      ["Mina", "'Mina', sans-serif"],
      ["Mingzat", "'Mingzat', sans-serif"],
      ["Miniver", "'Miniver', display"],
      ["Miriam Libre", "'Miriam Libre', sans-serif"],
      ["Mirza", "'Mirza', display"],
      ["Miss Fajardose", "'Miss Fajardose', handwriting"],
      ["Mitr", "'Mitr', sans-serif"],
      ["Mochiy Pop One", "'Mochiy Pop One', sans-serif"],
      ["Mochiy Pop P One", "'Mochiy Pop P One', sans-serif"],
      ["Modak", "'Modak', display"],
      ["Modern Antiqua", "'Modern Antiqua', display"],
      ["Mogra", "'Mogra', display"],
      ["Mohave", "'Mohave', sans-serif"],
      ["Molengo", "'Molengo', sans-serif"],
      ["Molle", "'Molle', handwriting"],
      ["Monda", "'Monda', sans-serif"],
      ["Monofett", "'Monofett', display"],
      ["Monoton", "'Monoton', display"],
      ["Monsieur La Doulaise", "'Monsieur La Doulaise', handwriting"],
      ["Montaga", "'Montaga', serif"],
      ["Montagu Slab", "'Montagu Slab', serif"],
      ["MonteCarlo", "'MonteCarlo', handwriting"],
      ["Montez", "'Montez', handwriting"],
      ["Montserrat", "'Montserrat', sans-serif"],
      ["Montserrat Alternates", "'Montserrat Alternates', sans-serif"],
      ["Montserrat Subrayada", "'Montserrat Subrayada', sans-serif"],
      ["Moo Lah Lah", "'Moo Lah Lah', display"],
      ["Moon Dance", "'Moon Dance', handwriting"],
      ["Moul", "'Moul', display"],
      ["Moulpali", "'Moulpali', display"],
      ["Mountains of Christmas", "'Mountains of Christmas', display"],
      ["Mouse Memoirs", "'Mouse Memoirs', sans-serif"],
      ["Mr Bedfort", "'Mr Bedfort', handwriting"],
      ["Mr Dafoe", "'Mr Dafoe', handwriting"],
      ["Mr De Haviland", "'Mr De Haviland', handwriting"],
      ["Mrs Saint Delafield", "'Mrs Saint Delafield', handwriting"],
      ["Mrs Sheppards", "'Mrs Sheppards', handwriting"],
      ["Ms Madi", "'Ms Madi', handwriting"],
      ["Mukta", "'Mukta', sans-serif"],
      ["Mukta Mahee", "'Mukta Mahee', sans-serif"],
      ["Mukta Malar", "'Mukta Malar', sans-serif"],
      ["Mukta Vaani", "'Mukta Vaani', sans-serif"],
      ["Mulish", "'Mulish', sans-serif"],
      ["Murecho", "'Murecho', sans-serif"],
      ["MuseoModerno", "'MuseoModerno', display"],
      ["My Soul", "'My Soul', handwriting"],
      ["Mystery Quest", "'Mystery Quest', display"],
      ["NTR", "'NTR', sans-serif"],
      ["Nanum Brush Script", "'Nanum Brush Script', handwriting"],
      ["Nanum Gothic", "'Nanum Gothic', sans-serif"],
      ["Nanum Gothic Coding", "'Nanum Gothic Coding', monospace"],
      ["Nanum Myeongjo", "'Nanum Myeongjo', serif"],
      ["Nanum Pen Script", "'Nanum Pen Script', handwriting"],
      ["Neonderthaw", "'Neonderthaw', handwriting"],
      ["Nerko One", "'Nerko One', handwriting"],
      ["Neucha", "'Neucha', handwriting"],
      ["Neuton", "'Neuton', serif"],
      ["New Rocker", "'New Rocker', display"],
      ["New Tegomin", "'New Tegomin', serif"],
      ["News Cycle", "'News Cycle', sans-serif"],
      ["Newsreader", "'Newsreader', serif"],
      ["Niconne", "'Niconne', handwriting"],
      ["Niramit", "'Niramit', sans-serif"],
      ["Nixie One", "'Nixie One', display"],
      ["Nobile", "'Nobile', sans-serif"],
      ["Nokora", "'Nokora', sans-serif"],
      ["Norican", "'Norican', handwriting"],
      ["Nosifer", "'Nosifer', display"],
      ["Notable", "'Notable', sans-serif"],
      ["Nothing You Could Do", "'Nothing You Could Do', handwriting"],
      ["Noticia Text", "'Noticia Text', serif"],
      ["Noto Emoji", "'Noto Emoji', sans-serif"],
      ["Noto Kufi Arabic", "'Noto Kufi Arabic', sans-serif"],
      ["Noto Music", "'Noto Music', sans-serif"],
      ["Noto Naskh Arabic", "'Noto Naskh Arabic', serif"],
      ["Noto Nastaliq Urdu", "'Noto Nastaliq Urdu', serif"],
      ["Noto Rashi Hebrew", "'Noto Rashi Hebrew', serif"],
      ["Noto Sans", "'Noto Sans', sans-serif"],
      ["Noto Sans Adlam", "'Noto Sans Adlam', sans-serif"],
      ["Noto Sans Adlam Unjoined", "'Noto Sans Adlam Unjoined', sans-serif"],
      ["Noto Sans Anatolian Hieroglyphs", "'Noto Sans Anatolian Hieroglyphs', sans-serif"],
      ["Noto Sans Arabic", "'Noto Sans Arabic', sans-serif"],
      ["Noto Sans Armenian", "'Noto Sans Armenian', sans-serif"],
      ["Noto Sans Avestan", "'Noto Sans Avestan', sans-serif"],
      ["Noto Sans Balinese", "'Noto Sans Balinese', sans-serif"],
      ["Noto Sans Bamum", "'Noto Sans Bamum', sans-serif"],
      ["Noto Sans Bassa Vah", "'Noto Sans Bassa Vah', sans-serif"],
      ["Noto Sans Batak", "'Noto Sans Batak', sans-serif"],
      ["Noto Sans Bengali", "'Noto Sans Bengali', sans-serif"],
      ["Noto Sans Bhaiksuki", "'Noto Sans Bhaiksuki', sans-serif"],
      ["Noto Sans Brahmi", "'Noto Sans Brahmi', sans-serif"],
      ["Noto Sans Buginese", "'Noto Sans Buginese', sans-serif"],
      ["Noto Sans Buhid", "'Noto Sans Buhid', sans-serif"],
      ["Noto Sans Canadian Aboriginal", "'Noto Sans Canadian Aboriginal', sans-serif"],
      ["Noto Sans Carian", "'Noto Sans Carian', sans-serif"],
      ["Noto Sans Caucasian Albanian", "'Noto Sans Caucasian Albanian', sans-serif"],
      ["Noto Sans Chakma", "'Noto Sans Chakma', sans-serif"],
      ["Noto Sans Cham", "'Noto Sans Cham', sans-serif"],
      ["Noto Sans Cherokee", "'Noto Sans Cherokee', sans-serif"],
      ["Noto Sans Coptic", "'Noto Sans Coptic', sans-serif"],
      ["Noto Sans Cuneiform", "'Noto Sans Cuneiform', sans-serif"],
      ["Noto Sans Cypriot", "'Noto Sans Cypriot', sans-serif"],
      ["Noto Sans Deseret", "'Noto Sans Deseret', sans-serif"],
      ["Noto Sans Devanagari", "'Noto Sans Devanagari', sans-serif"],
      ["Noto Sans Display", "'Noto Sans Display', sans-serif"],
      ["Noto Sans Duployan", "'Noto Sans Duployan', sans-serif"],
      ["Noto Sans Egyptian Hieroglyphs", "'Noto Sans Egyptian Hieroglyphs', sans-serif"],
      ["Noto Sans Elbasan", "'Noto Sans Elbasan', sans-serif"],
      ["Noto Sans Elymaic", "'Noto Sans Elymaic', sans-serif"],
      ["Noto Sans Georgian", "'Noto Sans Georgian', sans-serif"],
      ["Noto Sans Glagolitic", "'Noto Sans Glagolitic', sans-serif"],
      ["Noto Sans Gothic", "'Noto Sans Gothic', sans-serif"],
      ["Noto Sans Grantha", "'Noto Sans Grantha', sans-serif"],
      ["Noto Sans Gujarati", "'Noto Sans Gujarati', sans-serif"],
      ["Noto Sans Gunjala Gondi", "'Noto Sans Gunjala Gondi', sans-serif"],
      ["Noto Sans Gurmukhi", "'Noto Sans Gurmukhi', sans-serif"],
      ["Noto Sans HK", "'Noto Sans HK', sans-serif"],
      ["Noto Sans Hanifi Rohingya", "'Noto Sans Hanifi Rohingya', sans-serif"],
      ["Noto Sans Hanunoo", "'Noto Sans Hanunoo', sans-serif"],
      ["Noto Sans Hatran", "'Noto Sans Hatran', sans-serif"],
      ["Noto Sans Hebrew", "'Noto Sans Hebrew', sans-serif"],
      ["Noto Sans Imperial Aramaic", "'Noto Sans Imperial Aramaic', sans-serif"],
      ["Noto Sans Indic Siyaq Numbers", "'Noto Sans Indic Siyaq Numbers', sans-serif"],
      ["Noto Sans Inscriptional Pahlavi", "'Noto Sans Inscriptional Pahlavi', sans-serif"],
      ["Noto Sans Inscriptional Parthian", "'Noto Sans Inscriptional Parthian', sans-serif"],
      ["Noto Sans JP", "'Noto Sans JP', sans-serif"],
      ["Noto Sans Javanese", "'Noto Sans Javanese', sans-serif"],
      ["Noto Sans KR", "'Noto Sans KR', sans-serif"],
      ["Noto Sans Kaithi", "'Noto Sans Kaithi', sans-serif"],
      ["Noto Sans Kannada", "'Noto Sans Kannada', sans-serif"],
      ["Noto Sans Kayah Li", "'Noto Sans Kayah Li', sans-serif"],
      ["Noto Sans Kharoshthi", "'Noto Sans Kharoshthi', sans-serif"],
      ["Noto Sans Khmer", "'Noto Sans Khmer', sans-serif"],
      ["Noto Sans Khojki", "'Noto Sans Khojki', sans-serif"],
      ["Noto Sans Khudawadi", "'Noto Sans Khudawadi', sans-serif"],
      ["Noto Sans Lao", "'Noto Sans Lao', sans-serif"],
      ["Noto Sans Lepcha", "'Noto Sans Lepcha', sans-serif"],
      ["Noto Sans Limbu", "'Noto Sans Limbu', sans-serif"],
      ["Noto Sans Linear A", "'Noto Sans Linear A', sans-serif"],
      ["Noto Sans Linear B", "'Noto Sans Linear B', sans-serif"],
      ["Noto Sans Lisu", "'Noto Sans Lisu', sans-serif"],
      ["Noto Sans Lycian", "'Noto Sans Lycian', sans-serif"],
      ["Noto Sans Lydian", "'Noto Sans Lydian', sans-serif"],
      ["Noto Sans Mahajani", "'Noto Sans Mahajani', sans-serif"],
      ["Noto Sans Malayalam", "'Noto Sans Malayalam', sans-serif"],
      ["Noto Sans Mandaic", "'Noto Sans Mandaic', sans-serif"],
      ["Noto Sans Manichaean", "'Noto Sans Manichaean', sans-serif"],
      ["Noto Sans Marchen", "'Noto Sans Marchen', sans-serif"],
      ["Noto Sans Masaram Gondi", "'Noto Sans Masaram Gondi', sans-serif"],
      ["Noto Sans Math", "'Noto Sans Math', sans-serif"],
      ["Noto Sans Mayan Numerals", "'Noto Sans Mayan Numerals', sans-serif"],
      ["Noto Sans Medefaidrin", "'Noto Sans Medefaidrin', sans-serif"],
      ["Noto Sans Meetei Mayek", "'Noto Sans Meetei Mayek', sans-serif"],
      ["Noto Sans Meroitic", "'Noto Sans Meroitic', sans-serif"],
      ["Noto Sans Miao", "'Noto Sans Miao', sans-serif"],
      ["Noto Sans Modi", "'Noto Sans Modi', sans-serif"],
      ["Noto Sans Mongolian", "'Noto Sans Mongolian', sans-serif"],
      ["Noto Sans Mono", "'Noto Sans Mono', monospace"],
      ["Noto Sans Mro", "'Noto Sans Mro', sans-serif"],
      ["Noto Sans Multani", "'Noto Sans Multani', sans-serif"],
      ["Noto Sans Myanmar", "'Noto Sans Myanmar', sans-serif"],
      ["Noto Sans N Ko", "'Noto Sans N Ko', sans-serif"],
      ["Noto Sans Nabataean", "'Noto Sans Nabataean', sans-serif"],
      ["Noto Sans New Tai Lue", "'Noto Sans New Tai Lue', sans-serif"],
      ["Noto Sans Newa", "'Noto Sans Newa', sans-serif"],
      ["Noto Sans Nushu", "'Noto Sans Nushu', sans-serif"],
      ["Noto Sans Ogham", "'Noto Sans Ogham', sans-serif"],
      ["Noto Sans Ol Chiki", "'Noto Sans Ol Chiki', sans-serif"],
      ["Noto Sans Old Hungarian", "'Noto Sans Old Hungarian', sans-serif"],
      ["Noto Sans Old Italic", "'Noto Sans Old Italic', sans-serif"],
      ["Noto Sans Old North Arabian", "'Noto Sans Old North Arabian', sans-serif"],
      ["Noto Sans Old Permic", "'Noto Sans Old Permic', sans-serif"],
      ["Noto Sans Old Persian", "'Noto Sans Old Persian', sans-serif"],
      ["Noto Sans Old Sogdian", "'Noto Sans Old Sogdian', sans-serif"],
      ["Noto Sans Old South Arabian", "'Noto Sans Old South Arabian', sans-serif"],
      ["Noto Sans Old Turkic", "'Noto Sans Old Turkic', sans-serif"],
      ["Noto Sans Oriya", "'Noto Sans Oriya', sans-serif"],
      ["Noto Sans Osage", "'Noto Sans Osage', sans-serif"],
      ["Noto Sans Osmanya", "'Noto Sans Osmanya', sans-serif"],
      ["Noto Sans Pahawh Hmong", "'Noto Sans Pahawh Hmong', sans-serif"],
      ["Noto Sans Palmyrene", "'Noto Sans Palmyrene', sans-serif"],
      ["Noto Sans Pau Cin Hau", "'Noto Sans Pau Cin Hau', sans-serif"],
      ["Noto Sans Phags Pa", "'Noto Sans Phags Pa', sans-serif"],
      ["Noto Sans Phoenician", "'Noto Sans Phoenician', sans-serif"],
      ["Noto Sans Psalter Pahlavi", "'Noto Sans Psalter Pahlavi', sans-serif"],
      ["Noto Sans Rejang", "'Noto Sans Rejang', sans-serif"],
      ["Noto Sans Runic", "'Noto Sans Runic', sans-serif"],
      ["Noto Sans SC", "'Noto Sans SC', sans-serif"],
      ["Noto Sans Samaritan", "'Noto Sans Samaritan', sans-serif"],
      ["Noto Sans Saurashtra", "'Noto Sans Saurashtra', sans-serif"],
      ["Noto Sans Sharada", "'Noto Sans Sharada', sans-serif"],
      ["Noto Sans Shavian", "'Noto Sans Shavian', sans-serif"],
      ["Noto Sans Siddham", "'Noto Sans Siddham', sans-serif"],
      ["Noto Sans Sinhala", "'Noto Sans Sinhala', sans-serif"],
      ["Noto Sans Sogdian", "'Noto Sans Sogdian', sans-serif"],
      ["Noto Sans Sora Sompeng", "'Noto Sans Sora Sompeng', sans-serif"],
      ["Noto Sans Soyombo", "'Noto Sans Soyombo', sans-serif"],
      ["Noto Sans Sundanese", "'Noto Sans Sundanese', sans-serif"],
      ["Noto Sans Syloti Nagri", "'Noto Sans Syloti Nagri', sans-serif"],
      ["Noto Sans Symbols", "'Noto Sans Symbols', sans-serif"],
      ["Noto Sans Symbols 2", "'Noto Sans Symbols 2', sans-serif"],
      ["Noto Sans Syriac", "'Noto Sans Syriac', sans-serif"],
      ["Noto Sans TC", "'Noto Sans TC', sans-serif"],
      ["Noto Sans Tagalog", "'Noto Sans Tagalog', sans-serif"],
      ["Noto Sans Tagbanwa", "'Noto Sans Tagbanwa', sans-serif"],
      ["Noto Sans Tai Le", "'Noto Sans Tai Le', sans-serif"],
      ["Noto Sans Tai Tham", "'Noto Sans Tai Tham', sans-serif"],
      ["Noto Sans Tai Viet", "'Noto Sans Tai Viet', sans-serif"],
      ["Noto Sans Takri", "'Noto Sans Takri', sans-serif"],
      ["Noto Sans Tamil", "'Noto Sans Tamil', sans-serif"],
      ["Noto Sans Tamil Supplement", "'Noto Sans Tamil Supplement', sans-serif"],
      ["Noto Sans Telugu", "'Noto Sans Telugu', sans-serif"],
      ["Noto Sans Thaana", "'Noto Sans Thaana', sans-serif"],
      ["Noto Sans Thai", "'Noto Sans Thai', sans-serif"],
      ["Noto Sans Thai Looped", "'Noto Sans Thai Looped', sans-serif"],
      ["Noto Sans Tifinagh", "'Noto Sans Tifinagh', sans-serif"],
      ["Noto Sans Tirhuta", "'Noto Sans Tirhuta', sans-serif"],
      ["Noto Sans Ugaritic", "'Noto Sans Ugaritic', sans-serif"],
      ["Noto Sans Vai", "'Noto Sans Vai', sans-serif"],
      ["Noto Sans Wancho", "'Noto Sans Wancho', sans-serif"],
      ["Noto Sans Warang Citi", "'Noto Sans Warang Citi', sans-serif"],
      ["Noto Sans Yi", "'Noto Sans Yi', sans-serif"],
      ["Noto Sans Zanabazar Square", "'Noto Sans Zanabazar Square', sans-serif"],
      ["Noto Serif", "'Noto Serif', serif"],
      ["Noto Serif Ahom", "'Noto Serif Ahom', serif"],
      ["Noto Serif Armenian", "'Noto Serif Armenian', serif"],
      ["Noto Serif Balinese", "'Noto Serif Balinese', serif"],
      ["Noto Serif Bengali", "'Noto Serif Bengali', serif"],
      ["Noto Serif Devanagari", "'Noto Serif Devanagari', serif"],
      ["Noto Serif Display", "'Noto Serif Display', serif"],
      ["Noto Serif Dogra", "'Noto Serif Dogra', serif"],
      ["Noto Serif Ethiopic", "'Noto Serif Ethiopic', serif"],
      ["Noto Serif Georgian", "'Noto Serif Georgian', serif"],
      ["Noto Serif Grantha", "'Noto Serif Grantha', serif"],
      ["Noto Serif Gujarati", "'Noto Serif Gujarati', serif"],
      ["Noto Serif Gurmukhi", "'Noto Serif Gurmukhi', serif"],
      ["Noto Serif Hebrew", "'Noto Serif Hebrew', serif"],
      ["Noto Serif JP", "'Noto Serif JP', serif"],
      ["Noto Serif KR", "'Noto Serif KR', serif"],
      ["Noto Serif Kannada", "'Noto Serif Kannada', serif"],
      ["Noto Serif Khmer", "'Noto Serif Khmer', serif"],
      ["Noto Serif Lao", "'Noto Serif Lao', serif"],
      ["Noto Serif Malayalam", "'Noto Serif Malayalam', serif"],
      ["Noto Serif Myanmar", "'Noto Serif Myanmar', serif"],
      ["Noto Serif Nyiakeng Puachue Hmong", "'Noto Serif Nyiakeng Puachue Hmong', serif"],
      ["Noto Serif SC", "'Noto Serif SC', serif"],
      ["Noto Serif Sinhala", "'Noto Serif Sinhala', serif"],
      ["Noto Serif TC", "'Noto Serif TC', serif"],
      ["Noto Serif Tamil", "'Noto Serif Tamil', serif"],
      ["Noto Serif Tangut", "'Noto Serif Tangut', serif"],
      ["Noto Serif Telugu", "'Noto Serif Telugu', serif"],
      ["Noto Serif Thai", "'Noto Serif Thai', serif"],
      ["Noto Serif Tibetan", "'Noto Serif Tibetan', serif"],
      ["Noto Serif Yezidi", "'Noto Serif Yezidi', serif"],
      ["Noto Traditional Nushu", "'Noto Traditional Nushu', sans-serif"],
      ["Nova Cut", "'Nova Cut', display"],
      ["Nova Flat", "'Nova Flat', display"],
      ["Nova Mono", "'Nova Mono', monospace"],
      ["Nova Oval", "'Nova Oval', display"],
      ["Nova Round", "'Nova Round', display"],
      ["Nova Script", "'Nova Script', display"],
      ["Nova Slim", "'Nova Slim', display"],
      ["Nova Square", "'Nova Square', display"],
      ["Numans", "'Numans', sans-serif"],
      ["Nunito", "'Nunito', sans-serif"],
      ["Nunito Sans", "'Nunito Sans', sans-serif"],
      ["Nuosu SIL", "'Nuosu SIL', serif"],
      ["Odibee Sans", "'Odibee Sans', display"],
      ["Odor Mean Chey", "'Odor Mean Chey', serif"],
      ["Offside", "'Offside', display"],
      ["Oi", "'Oi', display"],
      ["Old Standard TT", "'Old Standard TT', serif"],
      ["Oldenburg", "'Oldenburg', display"],
      ["Ole", "'Ole', handwriting"],
      ["Oleo Script", "'Oleo Script', display"],
      ["Oleo Script Swash Caps", "'Oleo Script Swash Caps', display"],
      ["Oooh Baby", "'Oooh Baby', handwriting"],
      ["Open Sans", "'Open Sans', sans-serif"],
      ["Oranienbaum", "'Oranienbaum', serif"],
      ["Orbitron", "'Orbitron', sans-serif"],
      ["Oregano", "'Oregano', display"],
      ["Orelega One", "'Orelega One', display"],
      ["Orienta", "'Orienta', sans-serif"],
      ["Original Surfer", "'Original Surfer', display"],
      ["Oswald", "'Oswald', sans-serif"],
      ["Outfit", "'Outfit', sans-serif"],
      ["Over the Rainbow", "'Over the Rainbow', handwriting"],
      ["Overlock", "'Overlock', display"],
      ["Overlock SC", "'Overlock SC', display"],
      ["Overpass", "'Overpass', sans-serif"],
      ["Overpass Mono", "'Overpass Mono', monospace"],
      ["Ovo", "'Ovo', serif"],
      ["Oxanium", "'Oxanium', display"],
      ["Oxygen", "'Oxygen', sans-serif"],
      ["Oxygen Mono", "'Oxygen Mono', monospace"],
      ["PT Mono", "'PT Mono', monospace"],
      ["PT Sans", "'PT Sans', sans-serif"],
      ["PT Sans Caption", "'PT Sans Caption', sans-serif"],
      ["PT Sans Narrow", "'PT Sans Narrow', sans-serif"],
      ["PT Serif", "'PT Serif', serif"],
      ["PT Serif Caption", "'PT Serif Caption', serif"],
      ["Pacifico", "'Pacifico', handwriting"],
      ["Padauk", "'Padauk', sans-serif"],
      ["Palanquin", "'Palanquin', sans-serif"],
      ["Palanquin Dark", "'Palanquin Dark', sans-serif"],
      ["Pangolin", "'Pangolin', handwriting"],
      ["Paprika", "'Paprika', display"],
      ["Parisienne", "'Parisienne', handwriting"],
      ["Passero One", "'Passero One', display"],
      ["Passion One", "'Passion One', display"],
      ["Passions Conflict", "'Passions Conflict', handwriting"],
      ["Pathway Gothic One", "'Pathway Gothic One', sans-serif"],
      ["Patrick Hand", "'Patrick Hand', handwriting"],
      ["Patrick Hand SC", "'Patrick Hand SC', handwriting"],
      ["Pattaya", "'Pattaya', sans-serif"],
      ["Patua One", "'Patua One', display"],
      ["Pavanam", "'Pavanam', sans-serif"],
      ["Paytone One", "'Paytone One', sans-serif"],
      ["Peddana", "'Peddana', serif"],
      ["Peralta", "'Peralta', display"],
      ["Permanent Marker", "'Permanent Marker', handwriting"],
      ["Petemoss", "'Petemoss', handwriting"],
      ["Petit Formal Script", "'Petit Formal Script', handwriting"],
      ["Petrona", "'Petrona', serif"],
      ["Philosopher", "'Philosopher', sans-serif"],
      ["Piazzolla", "'Piazzolla', serif"],
      ["Piedra", "'Piedra', display"],
      ["Pinyon Script", "'Pinyon Script', handwriting"],
      ["Pirata One", "'Pirata One', display"],
      ["Plaster", "'Plaster', display"],
      ["Play", "'Play', sans-serif"],
      ["Playball", "'Playball', display"],
      ["Playfair Display", "'Playfair Display', serif"],
      ["Playfair Display SC", "'Playfair Display SC', serif"],
      ["Plus Jakarta Sans", "'Plus Jakarta Sans', sans-serif"],
      ["Podkova", "'Podkova', serif"],
      ["Poiret One", "'Poiret One', display"],
      ["Poller One", "'Poller One', display"],
      ["Poly", "'Poly', serif"],
      ["Pompiere", "'Pompiere', display"],
      ["Pontano Sans", "'Pontano Sans', sans-serif"],
      ["Poor Story", "'Poor Story', display"],
      ["Poppins", "'Poppins', sans-serif"],
      ["Port Lligat Sans", "'Port Lligat Sans', sans-serif"],
      ["Port Lligat Slab", "'Port Lligat Slab', serif"],
      ["Potta One", "'Potta One', display"],
      ["Pragati Narrow", "'Pragati Narrow', sans-serif"],
      ["Praise", "'Praise', handwriting"],
      ["Prata", "'Prata', serif"],
      ["Preahvihear", "'Preahvihear', sans-serif"],
      ["Press Start 2P", "'Press Start 2P', display"],
      ["Pridi", "'Pridi', serif"],
      ["Princess Sofia", "'Princess Sofia', handwriting"],
      ["Prociono", "'Prociono', serif"],
      ["Prompt", "'Prompt', sans-serif"],
      ["Prosto One", "'Prosto One', display"],
      ["Proza Libre", "'Proza Libre', sans-serif"],
      ["Public Sans", "'Public Sans', sans-serif"],
      ["Puppies Play", "'Puppies Play', handwriting"],
      ["Puritan", "'Puritan', sans-serif"],
      ["Purple Purse", "'Purple Purse', display"],
      ["Qahiri", "'Qahiri', sans-serif"],
      ["Quando", "'Quando', serif"],
      ["Quantico", "'Quantico', sans-serif"],
      ["Quattrocento", "'Quattrocento', serif"],
      ["Quattrocento Sans", "'Quattrocento Sans', sans-serif"],
      ["Questrial", "'Questrial', sans-serif"],
      ["Quicksand", "'Quicksand', sans-serif"],
      ["Quintessential", "'Quintessential', handwriting"],
      ["Qwigley", "'Qwigley', handwriting"],
      ["Qwitcher Grypen", "'Qwitcher Grypen', handwriting"],
      ["Racing Sans One", "'Racing Sans One', display"],
      ["Radio Canada", "'Radio Canada', sans-serif"],
      ["Radley", "'Radley', serif"],
      ["Rajdhani", "'Rajdhani', sans-serif"],
      ["Rakkas", "'Rakkas', display"],
      ["Raleway", "'Raleway', sans-serif"],
      ["Raleway Dots", "'Raleway Dots', display"],
      ["Ramabhadra", "'Ramabhadra', sans-serif"],
      ["Ramaraja", "'Ramaraja', serif"],
      ["Rambla", "'Rambla', sans-serif"],
      ["Rammetto One", "'Rammetto One', display"],
      ["Rampart One", "'Rampart One', display"],
      ["Ranchers", "'Ranchers', display"],
      ["Rancho", "'Rancho', handwriting"],
      ["Ranga", "'Ranga', display"],
      ["Rasa", "'Rasa', serif"],
      ["Rationale", "'Rationale', sans-serif"],
      ["Ravi Prakash", "'Ravi Prakash', display"],
      ["Readex Pro", "'Readex Pro', sans-serif"],
      ["Recursive", "'Recursive', sans-serif"],
      ["Red Hat Display", "'Red Hat Display', sans-serif"],
      ["Red Hat Mono", "'Red Hat Mono', monospace"],
      ["Red Hat Text", "'Red Hat Text', sans-serif"],
      ["Red Rose", "'Red Rose', display"],
      ["Redacted", "'Redacted', display"],
      ["Redacted Script", "'Redacted Script', display"],
      ["Redressed", "'Redressed', handwriting"],
      ["Reem Kufi", "'Reem Kufi', sans-serif"],
      ["Reenie Beanie", "'Reenie Beanie', handwriting"],
      ["Reggae One", "'Reggae One', display"],
      ["Revalia", "'Revalia', display"],
      ["Rhodium Libre", "'Rhodium Libre', serif"],
      ["Ribeye", "'Ribeye', display"],
      ["Ribeye Marrow", "'Ribeye Marrow', display"],
      ["Righteous", "'Righteous', display"],
      ["Risque", "'Risque', display"],
      ["Road Rage", "'Road Rage', display"],
      ["Roboto", "'Roboto', sans-serif"],
      ["Roboto Condensed", "'Roboto Condensed', sans-serif"],
      ["Roboto Flex", "'Roboto Flex', sans-serif"],
      ["Roboto Mono", "'Roboto Mono', monospace"],
      ["Roboto Serif", "'Roboto Serif', serif"],
      ["Roboto Slab", "'Roboto Slab', serif"],
      ["Rochester", "'Rochester', handwriting"],
      ["Rock Salt", "'Rock Salt', handwriting"],
      ["RocknRoll One", "'RocknRoll One', sans-serif"],
      ["Rokkitt", "'Rokkitt', serif"],
      ["Romanesco", "'Romanesco', handwriting"],
      ["Ropa Sans", "'Ropa Sans', sans-serif"],
      ["Rosario", "'Rosario', sans-serif"],
      ["Rosarivo", "'Rosarivo', serif"],
      ["Rouge Script", "'Rouge Script', handwriting"],
      ["Rowdies", "'Rowdies', display"],
      ["Rozha One", "'Rozha One', serif"],
      ["Rubik", "'Rubik', sans-serif"],
      ["Rubik Beastly", "'Rubik Beastly', display"],
      ["Rubik Bubbles", "'Rubik Bubbles', display"],
      ["Rubik Glitch", "'Rubik Glitch', display"],
      ["Rubik Microbe", "'Rubik Microbe', display"],
      ["Rubik Mono One", "'Rubik Mono One', sans-serif"],
      ["Rubik Moonrocks", "'Rubik Moonrocks', display"],
      ["Rubik Puddles", "'Rubik Puddles', display"],
      ["Rubik Wet Paint", "'Rubik Wet Paint', display"],
      ["Ruda", "'Ruda', sans-serif"],
      ["Rufina", "'Rufina', serif"],
      ["Ruge Boogie", "'Ruge Boogie', handwriting"],
      ["Ruluko", "'Ruluko', sans-serif"],
      ["Rum Raisin", "'Rum Raisin', sans-serif"],
      ["Ruslan Display", "'Ruslan Display', display"],
      ["Russo One", "'Russo One', sans-serif"],
      ["Ruthie", "'Ruthie', handwriting"],
      ["Rye", "'Rye', display"],
      ["STIX Two Text", "'STIX Two Text', serif"],
      ["Sacramento", "'Sacramento', handwriting"],
      ["Sahitya", "'Sahitya', serif"],
      ["Sail", "'Sail', display"],
      ["Saira", "'Saira', sans-serif"],
      ["Saira Condensed", "'Saira Condensed', sans-serif"],
      ["Saira Extra Condensed", "'Saira Extra Condensed', sans-serif"],
      ["Saira Semi Condensed", "'Saira Semi Condensed', sans-serif"],
      ["Saira Stencil One", "'Saira Stencil One', display"],
      ["Salsa", "'Salsa', display"],
      ["Sanchez", "'Sanchez', serif"],
      ["Sancreek", "'Sancreek', display"],
      ["Sansita", "'Sansita', sans-serif"],
      ["Sansita Swashed", "'Sansita Swashed', display"],
      ["Sarabun", "'Sarabun', sans-serif"],
      ["Sarala", "'Sarala', sans-serif"],
      ["Sarina", "'Sarina', display"],
      ["Sarpanch", "'Sarpanch', sans-serif"],
      ["Sassy Frass", "'Sassy Frass', handwriting"],
      ["Satisfy", "'Satisfy', handwriting"],
      ["Sawarabi Gothic", "'Sawarabi Gothic', sans-serif"],
      ["Sawarabi Mincho", "'Sawarabi Mincho', serif"],
      ["Scada", "'Scada', sans-serif"],
      ["Scheherazade New", "'Scheherazade New', serif"],
      ["Schoolbell", "'Schoolbell', handwriting"],
      ["Scope One", "'Scope One', serif"],
      ["Seaweed Script", "'Seaweed Script', display"],
      ["Secular One", "'Secular One', sans-serif"],
      ["Sedgwick Ave", "'Sedgwick Ave', handwriting"],
      ["Sedgwick Ave Display", "'Sedgwick Ave Display', handwriting"],
      ["Sen", "'Sen', sans-serif"],
      ["Send Flowers", "'Send Flowers', handwriting"],
      ["Sevillana", "'Sevillana', display"],
      ["Seymour One", "'Seymour One', sans-serif"],
      ["Shadows Into Light", "'Shadows Into Light', handwriting"],
      ["Shadows Into Light Two", "'Shadows Into Light Two', handwriting"],
      ["Shalimar", "'Shalimar', handwriting"],
      ["Shanti", "'Shanti', sans-serif"],
      ["Share", "'Share', display"],
      ["Share Tech", "'Share Tech', sans-serif"],
      ["Share Tech Mono", "'Share Tech Mono', monospace"],
      ["Shippori Antique", "'Shippori Antique', sans-serif"],
      ["Shippori Antique B1", "'Shippori Antique B1', sans-serif"],
      ["Shippori Mincho", "'Shippori Mincho', serif"],
      ["Shippori Mincho B1", "'Shippori Mincho B1', serif"],
      ["Shojumaru", "'Shojumaru', display"],
      ["Short Stack", "'Short Stack', handwriting"],
      ["Shrikhand", "'Shrikhand', display"],
      ["Siemreap", "'Siemreap', display"],
      ["Sigmar One", "'Sigmar One', display"],
      ["Signika", "'Signika', sans-serif"],
      ["Signika Negative", "'Signika Negative', sans-serif"],
      ["Simonetta", "'Simonetta', display"],
      ["Single Day", "'Single Day', display"],
      ["Sintony", "'Sintony', sans-serif"],
      ["Sirin Stencil", "'Sirin Stencil', display"],
      ["Six Caps", "'Six Caps', sans-serif"],
      ["Skranji", "'Skranji', display"],
      ["Slabo 13px", "'Slabo 13px', serif"],
      ["Slabo 27px", "'Slabo 27px', serif"],
      ["Slackey", "'Slackey', display"],
      ["Smokum", "'Smokum', display"],
      ["Smooch", "'Smooch', handwriting"],
      ["Smooch Sans", "'Smooch Sans', sans-serif"],
      ["Smythe", "'Smythe', display"],
      ["Sniglet", "'Sniglet', display"],
      ["Snippet", "'Snippet', sans-serif"],
      ["Snowburst One", "'Snowburst One', display"],
      ["Sofadi One", "'Sofadi One', display"],
      ["Sofia", "'Sofia', handwriting"],
      ["Solway", "'Solway', serif"],
      ["Song Myung", "'Song Myung', serif"],
      ["Sonsie One", "'Sonsie One', display"],
      ["Sora", "'Sora', sans-serif"],
      ["Sorts Mill Goudy", "'Sorts Mill Goudy', serif"],
      ["Source Code Pro", "'Source Code Pro', monospace"],
      ["Source Sans 3", "'Source Sans 3', sans-serif"],
      ["Source Sans Pro", "'Source Sans Pro', sans-serif"],
      ["Source Serif 4", "'Source Serif 4', serif"],
      ["Source Serif Pro", "'Source Serif Pro', serif"],
      ["Space Grotesk", "'Space Grotesk', sans-serif"],
      ["Space Mono", "'Space Mono', monospace"],
      ["Special Elite", "'Special Elite', display"],
      ["Spectral", "'Spectral', serif"],
      ["Spectral SC", "'Spectral SC', serif"],
      ["Spicy Rice", "'Spicy Rice', display"],
      ["Spinnaker", "'Spinnaker', sans-serif"],
      ["Spirax", "'Spirax', display"],
      ["Splash", "'Splash', handwriting"],
      ["Spline Sans", "'Spline Sans', sans-serif"],
      ["Spline Sans Mono", "'Spline Sans Mono', monospace"],
      ["Squada One", "'Squada One', display"],
      ["Square Peg", "'Square Peg', handwriting"],
      ["Sree Krushnadevaraya", "'Sree Krushnadevaraya', serif"],
      ["Sriracha", "'Sriracha', handwriting"],
      ["Srisakdi", "'Srisakdi', display"],
      ["Staatliches", "'Staatliches', display"],
      ["Stalemate", "'Stalemate', handwriting"],
      ["Stalinist One", "'Stalinist One', display"],
      ["Stardos Stencil", "'Stardos Stencil', display"],
      ["Stick", "'Stick', sans-serif"],
      ["Stick No Bills", "'Stick No Bills', sans-serif"],
      ["Stint Ultra Condensed", "'Stint Ultra Condensed', display"],
      ["Stint Ultra Expanded", "'Stint Ultra Expanded', display"],
      ["Stoke", "'Stoke', serif"],
      ["Strait", "'Strait', sans-serif"],
      ["Style Script", "'Style Script', handwriting"],
      ["Stylish", "'Stylish', sans-serif"],
      ["Sue Ellen Francisco", "'Sue Ellen Francisco', handwriting"],
      ["Suez One", "'Suez One', serif"],
      ["Sulphur Point", "'Sulphur Point', sans-serif"],
      ["Sumana", "'Sumana', serif"],
      ["Sunflower", "'Sunflower', sans-serif"],
      ["Sunshiney", "'Sunshiney', handwriting"],
      ["Supermercado One", "'Supermercado One', display"],
      ["Sura", "'Sura', serif"],
      ["Suranna", "'Suranna', serif"],
      ["Suravaram", "'Suravaram', serif"],
      ["Suwannaphum", "'Suwannaphum', serif"],
      ["Swanky and Moo Moo", "'Swanky and Moo Moo', handwriting"],
      ["Syncopate", "'Syncopate', sans-serif"],
      ["Syne", "'Syne', sans-serif"],
      ["Syne Mono", "'Syne Mono', monospace"],
      ["Syne Tactile", "'Syne Tactile', display"],
      ["Tai Heritage Pro", "'Tai Heritage Pro', serif"],
      ["Tajawal", "'Tajawal', sans-serif"],
      ["Tangerine", "'Tangerine', handwriting"],
      ["Tapestry", "'Tapestry', handwriting"],
      ["Taprom", "'Taprom', display"],
      ["Tauri", "'Tauri', sans-serif"],
      ["Taviraj", "'Taviraj', serif"],
      ["Teko", "'Teko', sans-serif"],
      ["Telex", "'Telex', sans-serif"],
      ["Tenali Ramakrishna", "'Tenali Ramakrishna', sans-serif"],
      ["Tenor Sans", "'Tenor Sans', sans-serif"],
      ["Text Me One", "'Text Me One', sans-serif"],
      ["Texturina", "'Texturina', serif"],
      ["Thasadith", "'Thasadith', sans-serif"],
      ["The Girl Next Door", "'The Girl Next Door', handwriting"],
      ["The Nautigal", "'The Nautigal', handwriting"],
      ["Tienne", "'Tienne', serif"],
      ["Tillana", "'Tillana', handwriting"],
      ["Timmana", "'Timmana', sans-serif"],
      ["Tinos", "'Tinos', serif"],
      ["Tiro Bangla", "'Tiro Bangla', serif"],
      ["Tiro Devanagari Hindi", "'Tiro Devanagari Hindi', serif"],
      ["Tiro Devanagari Marathi", "'Tiro Devanagari Marathi', serif"],
      ["Tiro Devanagari Sanskrit", "'Tiro Devanagari Sanskrit', serif"],
      ["Tiro Gurmukhi", "'Tiro Gurmukhi', serif"],
      ["Tiro Kannada", "'Tiro Kannada', serif"],
      ["Tiro Tamil", "'Tiro Tamil', serif"],
      ["Tiro Telugu", "'Tiro Telugu', serif"],
      ["Titan One", "'Titan One', display"],
      ["Titillium Web", "'Titillium Web', sans-serif"],
      ["Tomorrow", "'Tomorrow', sans-serif"],
      ["Tourney", "'Tourney', display"],
      ["Trade Winds", "'Trade Winds', display"],
      ["Train One", "'Train One', display"],
      ["Trirong", "'Trirong', serif"],
      ["Trispace", "'Trispace', sans-serif"],
      ["Trocchi", "'Trocchi', serif"],
      ["Trochut", "'Trochut', display"],
      ["Truculenta", "'Truculenta', sans-serif"],
      ["Trykker", "'Trykker', serif"],
      ["Tulpen One", "'Tulpen One', display"],
      ["Turret Road", "'Turret Road', display"],
      ["Twinkle Star", "'Twinkle Star', handwriting"],
      ["Ubuntu", "'Ubuntu', sans-serif"],
      ["Ubuntu Condensed", "'Ubuntu Condensed', sans-serif"],
      ["Ubuntu Mono", "'Ubuntu Mono', monospace"],
      ["Uchen", "'Uchen', serif"],
      ["Ultra", "'Ultra', serif"],
      ["Uncial Antiqua", "'Uncial Antiqua', display"],
      ["Underdog", "'Underdog', display"],
      ["Unica One", "'Unica One', display"],
      ["UnifrakturCook", "'UnifrakturCook', display"],
      ["UnifrakturMaguntia", "'UnifrakturMaguntia', display"],
      ["Unkempt", "'Unkempt', display"],
      ["Unlock", "'Unlock', display"],
      ["Unna", "'Unna', serif"],
      ["Updock", "'Updock', handwriting"],
      ["Urbanist", "'Urbanist', sans-serif"],
      ["VT323", "'VT323', monospace"],
      ["Vampiro One", "'Vampiro One', display"],
      ["Varela", "'Varela', sans-serif"],
      ["Varela Round", "'Varela Round', sans-serif"],
      ["Varta", "'Varta', sans-serif"],
      ["Vast Shadow", "'Vast Shadow', display"],
      ["Vazirmatn", "'Vazirmatn', sans-serif"],
      ["Vesper Libre", "'Vesper Libre', serif"],
      ["Viaoda Libre", "'Viaoda Libre', display"],
      ["Vibes", "'Vibes', display"],
      ["Vibur", "'Vibur', handwriting"],
      ["Vidaloka", "'Vidaloka', serif"],
      ["Viga", "'Viga', sans-serif"],
      ["Voces", "'Voces', display"],
      ["Volkhov", "'Volkhov', serif"],
      ["Vollkorn", "'Vollkorn', serif"],
      ["Vollkorn SC", "'Vollkorn SC', serif"],
      ["Voltaire", "'Voltaire', sans-serif"],
      ["Vujahday Script", "'Vujahday Script', handwriting"],
      ["Waiting for the Sunrise", "'Waiting for the Sunrise', handwriting"],
      ["Wallpoet", "'Wallpoet', display"],
      ["Walter Turncoat", "'Walter Turncoat', handwriting"],
      ["Warnes", "'Warnes', display"],
      ["Water Brush", "'Water Brush', handwriting"],
      ["Waterfall", "'Waterfall', handwriting"],
      ["Wellfleet", "'Wellfleet', display"],
      ["Wendy One", "'Wendy One', sans-serif"],
      ["Whisper", "'Whisper', handwriting"],
      ["WindSong", "'WindSong', handwriting"],
      ["Wire One", "'Wire One', sans-serif"],
      ["Work Sans", "'Work Sans', sans-serif"],
      ["Xanh Mono", "'Xanh Mono', monospace"],
      ["Yaldevi", "'Yaldevi', sans-serif"],
      ["Yanone Kaffeesatz", "'Yanone Kaffeesatz', sans-serif"],
      ["Yantramanav", "'Yantramanav', sans-serif"],
      ["Yatra One", "'Yatra One', display"],
      ["Yellowtail", "'Yellowtail', handwriting"],
      ["Yeon Sung", "'Yeon Sung', display"],
      ["Yeseva One", "'Yeseva One', display"],
      ["Yesteryear", "'Yesteryear', handwriting"],
      ["Yomogi", "'Yomogi', handwriting"],
      ["Yrsa", "'Yrsa', serif"],
      ["Yuji Boku", "'Yuji Boku', serif"],
      ["Yuji Mai", "'Yuji Mai', serif"],
      ["Yuji Syuku", "'Yuji Syuku', serif"],
      ["Yusei Magic", "'Yusei Magic', sans-serif"],
      ["ZCOOL KuaiLe", "'ZCOOL KuaiLe', display"],
      ["ZCOOL QingKe HuangYou", "'ZCOOL QingKe HuangYou', display"],
      ["ZCOOL XiaoWei", "'ZCOOL XiaoWei', serif"],
      ["Zen Antique", "'Zen Antique', serif"],
      ["Zen Antique Soft", "'Zen Antique Soft', serif"],
      ["Zen Dots", "'Zen Dots', display"],
      ["Zen Kaku Gothic Antique", "'Zen Kaku Gothic Antique', sans-serif"],
      ["Zen Kaku Gothic New", "'Zen Kaku Gothic New', sans-serif"],
      ["Zen Kurenaido", "'Zen Kurenaido', sans-serif"],
      ["Zen Loop", "'Zen Loop', display"],
      ["Zen Maru Gothic", "'Zen Maru Gothic', sans-serif"],
      ["Zen Old Mincho", "'Zen Old Mincho', serif"],
      ["Zen Tokyo Zoo", "'Zen Tokyo Zoo', display"],
      ["Zeyada", "'Zeyada', handwriting"],
      ["Zhi Mang Xing", "'Zhi Mang Xing', handwriting"],
      ["Zilla Slab", "'Zilla Slab', serif"],
      ["Zilla Slab Highlight", "'Zilla Slab Highlight', display"]
    ]
  end
end
